//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        public Almacen()
        {
            this.Kardex = new HashSet<Kardex>();
            this.NotaSalida = new HashSet<NotaSalida>();
            this.Ubicacion = new HashSet<Ubicacion>();
        }
    
        public int IdAlmacen { get; set; }
        public string NombreAlmacen { get; set; }
        public string Direccion { get; set; }
        public string UsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaRegsitro { get; set; }
    
        public virtual ICollection<Kardex> Kardex { get; set; }
        public virtual ICollection<NotaSalida> NotaSalida { get; set; }
        public virtual ICollection<Ubicacion> Ubicacion { get; set; }
    }
}
