//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public Productos()
        {
            this.DetalleNotaSalida = new HashSet<DetalleNotaSalida>();
            this.DetallePedido = new HashSet<DetallePedido>();
        }
    
        public int idProducto { get; set; }
        public string Descripcion { get; set; }
        public string UnidadMedida { get; set; }
        public string Presentacion { get; set; }
    
        public virtual ICollection<DetalleNotaSalida> DetalleNotaSalida { get; set; }
        public virtual ICollection<DetallePedido> DetallePedido { get; set; }
    }
}
