#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByS.RHumanos.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_ByS")]
	public partial class _DBMLRHumanosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public _DBMLRHumanosDataContext() : 
				base(global::ByS.RHumanos.Data.Properties.Settings.Default.BD_BySConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public _DBMLRHumanosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _DBMLRHumanosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _DBMLRHumanosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _DBMLRHumanosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="RecursosHumanos.pa_S_Area")]
		public ISingleResult<pa_S_AreaResult> pa_S_Area()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<pa_S_AreaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="RecursosHumanos.pa_S_Empleado")]
		public ISingleResult<pa_S_EmpleadoResult> pa_S_Empleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codArea, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string p_desNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string p_desApellido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codEmpleado, p_codArea, p_desNombre, p_desApellido);
			return ((ISingleResult<pa_S_EmpleadoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="RecursosHumanos.pa_S_EmpleadoLogin")]
		public ISingleResult<pa_S_EmpleadoLoginResult> pa_S_EmpleadoLogin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_desLogin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_desLogin);
			return ((ISingleResult<pa_S_EmpleadoLoginResult>)(result.ReturnValue));
		}
	}
	
	public partial class pa_S_AreaResult
	{
		
		private int _codArea;
		
		private string _desNombre;
		
		private string _gloDescripcion;
		
		private bool _indActivo;
		
		private string _segUsuarioCrea;
		
		private string _segUsuarioEdita;
		
		private System.DateTime _segFechaCrea;
		
		private System.Nullable<System.DateTime> _segFechaEdita;
		
		private string _segMaquinaOrigen;
		
		private bool _indEliminado;
		
		public pa_S_AreaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codArea", DbType="Int NOT NULL")]
		public int codArea
		{
			get
			{
				return this._codArea;
			}
			set
			{
				if ((this._codArea != value))
				{
					this._codArea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desNombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string desNombre
		{
			get
			{
				return this._desNombre;
			}
			set
			{
				if ((this._desNombre != value))
				{
					this._desNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gloDescripcion", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string gloDescripcion
		{
			get
			{
				return this._gloDescripcion;
			}
			set
			{
				if ((this._gloDescripcion != value))
				{
					this._gloDescripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indActivo", DbType="Bit NOT NULL")]
		public bool indActivo
		{
			get
			{
				return this._indActivo;
			}
			set
			{
				if ((this._indActivo != value))
				{
					this._indActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioCrea", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segUsuarioCrea
		{
			get
			{
				return this._segUsuarioCrea;
			}
			set
			{
				if ((this._segUsuarioCrea != value))
				{
					this._segUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioEdita", DbType="VarChar(25)")]
		public string segUsuarioEdita
		{
			get
			{
				return this._segUsuarioEdita;
			}
			set
			{
				if ((this._segUsuarioEdita != value))
				{
					this._segUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaCrea", DbType="DateTime NOT NULL")]
		public System.DateTime segFechaCrea
		{
			get
			{
				return this._segFechaCrea;
			}
			set
			{
				if ((this._segFechaCrea != value))
				{
					this._segFechaCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> segFechaEdita
		{
			get
			{
				return this._segFechaEdita;
			}
			set
			{
				if ((this._segFechaEdita != value))
				{
					this._segFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segMaquinaOrigen", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segMaquinaOrigen
		{
			get
			{
				return this._segMaquinaOrigen;
			}
			set
			{
				if ((this._segMaquinaOrigen != value))
				{
					this._segMaquinaOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indEliminado", DbType="Bit NOT NULL")]
		public bool indEliminado
		{
			get
			{
				return this._indEliminado;
			}
			set
			{
				if ((this._indEliminado != value))
				{
					this._indEliminado = value;
				}
			}
		}
	}
	
	public partial class pa_S_EmpleadoResult
	{
		
		private int _codEmpleado;
		
		private int _codPersona;
		
		private int _codCargo;
		
		private string _codCargoNombre;
		
		private int _codArea;
		
		private string _codAreaNombre;
		
		private string _desNombre;
		
		private string _desApellido;
		
		private bool _indActivo;
		
		private string _segUsuarioCrea;
		
		private string _segUsuarioEdita;
		
		private System.DateTime _segFechaCrea;
		
		private System.Nullable<System.DateTime> _segFechaEdita;
		
		private string _segMaquinaOrigen;
		
		private bool _indEliminado;
		
		public pa_S_EmpleadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleado", DbType="Int NOT NULL")]
		public int codEmpleado
		{
			get
			{
				return this._codEmpleado;
			}
			set
			{
				if ((this._codEmpleado != value))
				{
					this._codEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPersona", DbType="Int NOT NULL")]
		public int codPersona
		{
			get
			{
				return this._codPersona;
			}
			set
			{
				if ((this._codPersona != value))
				{
					this._codPersona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCargo", DbType="Int NOT NULL")]
		public int codCargo
		{
			get
			{
				return this._codCargo;
			}
			set
			{
				if ((this._codCargo != value))
				{
					this._codCargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCargoNombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string codCargoNombre
		{
			get
			{
				return this._codCargoNombre;
			}
			set
			{
				if ((this._codCargoNombre != value))
				{
					this._codCargoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codArea", DbType="Int NOT NULL")]
		public int codArea
		{
			get
			{
				return this._codArea;
			}
			set
			{
				if ((this._codArea != value))
				{
					this._codArea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codAreaNombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string codAreaNombre
		{
			get
			{
				return this._codAreaNombre;
			}
			set
			{
				if ((this._codAreaNombre != value))
				{
					this._codAreaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desNombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string desNombre
		{
			get
			{
				return this._desNombre;
			}
			set
			{
				if ((this._desNombre != value))
				{
					this._desNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desApellido", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string desApellido
		{
			get
			{
				return this._desApellido;
			}
			set
			{
				if ((this._desApellido != value))
				{
					this._desApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indActivo", DbType="Bit NOT NULL")]
		public bool indActivo
		{
			get
			{
				return this._indActivo;
			}
			set
			{
				if ((this._indActivo != value))
				{
					this._indActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioCrea", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segUsuarioCrea
		{
			get
			{
				return this._segUsuarioCrea;
			}
			set
			{
				if ((this._segUsuarioCrea != value))
				{
					this._segUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioEdita", DbType="VarChar(25)")]
		public string segUsuarioEdita
		{
			get
			{
				return this._segUsuarioEdita;
			}
			set
			{
				if ((this._segUsuarioEdita != value))
				{
					this._segUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaCrea", DbType="DateTime NOT NULL")]
		public System.DateTime segFechaCrea
		{
			get
			{
				return this._segFechaCrea;
			}
			set
			{
				if ((this._segFechaCrea != value))
				{
					this._segFechaCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> segFechaEdita
		{
			get
			{
				return this._segFechaEdita;
			}
			set
			{
				if ((this._segFechaEdita != value))
				{
					this._segFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segMaquinaOrigen", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segMaquinaOrigen
		{
			get
			{
				return this._segMaquinaOrigen;
			}
			set
			{
				if ((this._segMaquinaOrigen != value))
				{
					this._segMaquinaOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indEliminado", DbType="Bit NOT NULL")]
		public bool indEliminado
		{
			get
			{
				return this._indEliminado;
			}
			set
			{
				if ((this._indEliminado != value))
				{
					this._indEliminado = value;
				}
			}
		}
	}
	
	public partial class pa_S_EmpleadoLoginResult
	{
		
		private int _codEmpleado;
		
		private int _codCargo;
		
		private int _codArea;
		
		private string _desNombre;
		
		private string _desApellido;
		
		public pa_S_EmpleadoLoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleado", DbType="Int NOT NULL")]
		public int codEmpleado
		{
			get
			{
				return this._codEmpleado;
			}
			set
			{
				if ((this._codEmpleado != value))
				{
					this._codEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCargo", DbType="Int NOT NULL")]
		public int codCargo
		{
			get
			{
				return this._codCargo;
			}
			set
			{
				if ((this._codCargo != value))
				{
					this._codCargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codArea", DbType="Int NOT NULL")]
		public int codArea
		{
			get
			{
				return this._codArea;
			}
			set
			{
				if ((this._codArea != value))
				{
					this._codArea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desNombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string desNombre
		{
			get
			{
				return this._desNombre;
			}
			set
			{
				if ((this._desNombre != value))
				{
					this._desNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desApellido", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string desApellido
		{
			get
			{
				return this._desApellido;
			}
			set
			{
				if ((this._desApellido != value))
				{
					this._desApellido = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
