//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models.Trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class FichaTecnicaProductoFarmacia
    {
        public FichaTecnicaProductoFarmacia()
        {
            this.Trazabilidad = new HashSet<Trazabilidad>();
        }
    
        public string codigoFichaTecProducto { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string etiquetado { get; set; }
        public string procedimientoAlmacen { get; set; }
        public string procedimientoVenta { get; set; }
        public string procedimiemtoDistribucion { get; set; }
        public string posologia { get; set; }
        public string quimicoFarmaceutico { get; set; }
        public string aprobar { get; set; }
        public string codigoProcedimiento { get; set; }
        public string codigoFichaTecProveedor { get; set; }
    
        public virtual FichaTecnicaProductoProveedor FichaTecnicaProductoProveedor { get; set; }
        public virtual Procedimiento Procedimiento { get; set; }
        public virtual ICollection<Trazabilidad> Trazabilidad { get; set; }
    }
}
