//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models.Trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class FichaTecnicaProductoProveedor
    {
        public FichaTecnicaProductoProveedor()
        {
            this.FichaTecnicaProductoFarmacia = new HashSet<FichaTecnicaProductoFarmacia>();
        }
    
        public string codigoFichaTecProveedor { get; set; }
        public string nombre { get; set; }
        public string nomTecnico { get; set; }
        public string modoUso { get; set; }
        public string contraIndicacion { get; set; }
        public string condicionesUso { get; set; }
        public string condicionesAlmacen { get; set; }
        public string condicionesComercial { get; set; }
        public string temperaturaMinima { get; set; }
        public string temperaturaMaxima { get; set; }
        public string laboratorioOrigen { get; set; }
    
        public virtual ICollection<FichaTecnicaProductoFarmacia> FichaTecnicaProductoFarmacia { get; set; }
    }
}
