//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models.Trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeTrazabilidad
    {
        public string codigoInformeTrazabilidad { get; set; }
        public string codigoProducto { get; set; }
        public string detalleAnalisis { get; set; }
        public string anexo { get; set; }
        public string codigoTraza { get; set; }
    
        public virtual Trazabilidad Trazabilidad { get; set; }
    }
}
