//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models.Trazabilidad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelGrupo2Entities : DbContext
    {
        public ModelGrupo2Entities()
            : base("name=ModelGrupo2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FichaTecnicaProductoFarmacia> FichaTecnicaProductoFarmacia { get; set; }
        public virtual DbSet<FichaTecnicaProductoProveedor> FichaTecnicaProductoProveedor { get; set; }
        public virtual DbSet<HojaMerma> HojaMerma { get; set; }
        public virtual DbSet<InformeTrazabilidad> InformeTrazabilidad { get; set; }
        public virtual DbSet<InformeVenta> InformeVenta { get; set; }
        public virtual DbSet<Kardex> Kardex { get; set; }
        public virtual DbSet<LibroReceta> LibroReceta { get; set; }
        public virtual DbSet<OrdenDeCompra> OrdenDeCompra { get; set; }
        public virtual DbSet<OrdenDeDespacho> OrdenDeDespacho { get; set; }
        public virtual DbSet<Procedimiento> Procedimiento { get; set; }
        public virtual DbSet<Trazabilidad> Trazabilidad { get; set; }
    }
}
