//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBS.Models.Trazabilidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trazabilidad
    {
        public Trazabilidad()
        {
            this.InformeTrazabilidad = new HashSet<InformeTrazabilidad>();
        }
    
        public string codigoTraza { get; set; }
        public Nullable<System.DateTime> fechaTraza { get; set; }
        public string codigoVenta { get; set; }
        public string numeroKardex { get; set; }
        public string codigoCompra { get; set; }
        public string numeroOrden { get; set; }
        public string numeroHojaMerma { get; set; }
        public string codigoProducto { get; set; }
        public string codigoFichaTecProducto { get; set; }
    
        public virtual FichaTecnicaProductoFarmacia FichaTecnicaProductoFarmacia { get; set; }
        public virtual HojaMerma HojaMerma { get; set; }
        public virtual ICollection<InformeTrazabilidad> InformeTrazabilidad { get; set; }
        public virtual InformeVenta InformeVenta { get; set; }
        public virtual Kardex Kardex { get; set; }
        public virtual LibroReceta LibroReceta { get; set; }
        public virtual OrdenDeCompra OrdenDeCompra { get; set; }
        public virtual OrdenDeDespacho OrdenDeDespacho { get; set; }
    }
}
