#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByS.Trazabilidad.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_ByS")]
	public partial class _DBMLTrazabilidadDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public _DBMLTrazabilidadDataContext() : 
				base(global::ByS.Trazabilidad.Data.Properties.Settings.Default.BD_BySConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public _DBMLTrazabilidadDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _DBMLTrazabilidadDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _DBMLTrazabilidadDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _DBMLTrazabilidadDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_S_Kardex")]
		public ISingleResult<pa_S_KardexResult> pa_S_Kardex([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_fechaIni, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_fechaFin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codProducto, p_fechaIni, p_fechaFin);
			return ((ISingleResult<pa_S_KardexResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_S_OrdendeCompra")]
		public ISingleResult<pa_S_OrdendeCompraResult> pa_S_OrdendeCompra([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_fechaIni, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_fechaFin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codProducto, p_fechaIni, p_fechaFin);
			return ((ISingleResult<pa_S_OrdendeCompraResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_S_OrdenDeDespacho")]
		public ISingleResult<pa_S_OrdenDeDespachoResult> pa_S_OrdenDeDespacho([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_fechaIni, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_fechaFin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codProducto, p_fechaIni, p_fechaFin);
			return ((ISingleResult<pa_S_OrdenDeDespachoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_S_HojaMerma")]
		public ISingleResult<pa_S_HojaMermaResult> pa_S_HojaMerma([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_fechaIni, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_fechaFin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codProducto, p_fechaIni, p_fechaFin);
			return ((ISingleResult<pa_S_HojaMermaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_S_InformeVenta")]
		public ISingleResult<pa_S_InformeVentaResult> pa_S_InformeVenta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_fechaIni, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_fechaFin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codProducto, p_fechaIni, p_fechaFin);
			return ((ISingleResult<pa_S_InformeVentaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_S_Producto")]
		public ISingleResult<pa_S_ProductoResult> pa_S_Producto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_nomProducto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codProducto, p_nomProducto);
			return ((ISingleResult<pa_S_ProductoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_S_FichaTecnicaProductoFarmacia")]
		public ISingleResult<pa_S_FichaTecnicaProductoFarmaciaResult> pa_S_FichaTecnicaProductoFarmacia([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codProducto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codProducto);
			return ((ISingleResult<pa_S_FichaTecnicaProductoFarmaciaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_U_FichaTecnicaProductoFarmacia")]
		public int pa_U_FichaTecnicaProductoFarmacia([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codigoFichaTecProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_etiquetado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string p_procedimientoAlmacen, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string p_procedimientoVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string p_procedimiemtoDistribucion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_posologia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_quimicoFarmaceutico, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_aprobar)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codigoFichaTecProducto, p_nombre, p_descripcion, p_etiquetado, p_procedimientoAlmacen, p_procedimientoVenta, p_procedimiemtoDistribucion, p_posologia, p_quimicoFarmaceutico, p_aprobar);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_U_Trazabilidad")]
		public int pa_U_Trazabilidad([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codigotraza, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_producto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string p_descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codigotraza, p_producto, p_descripcion, p_estado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_I_Trazabilidad")]
		public int pa_I_Trazabilidad([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] ref string p_codigoTraza, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_producto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string p_descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codigoTraza, p_producto, p_descripcion, p_estado);
			p_codigoTraza = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_I_TrazabilidadDetalle")]
		public int pa_I_TrazabilidadDetalle([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codigoTraza, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codigoVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_numeroKardex, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codigoCompra, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_numeroOrden, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_numeroHojaMerma, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_nombreProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codigoFichaTecProducto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codigoTraza, p_codigoVenta, p_numeroKardex, p_codigoCompra, p_numeroOrden, p_numeroHojaMerma, p_nombreProducto, p_codigoFichaTecProducto);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_S_UsuarioTrazabilidad")]
		public ISingleResult<pa_S_UsuarioTrazabilidadResult> pa_S_UsuarioTrazabilidad([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codCargo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codArea)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codCargo, p_codArea);
			return ((ISingleResult<pa_S_UsuarioTrazabilidadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_I_InformeTrazabilidad")]
		public int pa_I_InformeTrazabilidad([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] ref string p_codigoinformeTrazabilidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_producto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string p_detalleAnalisis, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_anexo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codigoTraza)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codigoinformeTrazabilidad, p_producto, p_detalleAnalisis, p_anexo, p_codigoTraza);
			p_codigoinformeTrazabilidad = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_S_Procedimiento")]
		public ISingleResult<pa_S_ProcedimientoResult> pa_S_Procedimiento([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codProducto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codProducto);
			return ((ISingleResult<pa_S_ProcedimientoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_I_OrdenRetiro")]
		public int pa_I_OrdenRetiro([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string codigoProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string autorizado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string motivo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string riesgo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigoProducto, fecha, autorizado, motivo, riesgo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_S_Trazabilidad")]
		public ISingleResult<pa_S_TrazabilidadResult> pa_S_Trazabilidad([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codProducto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codProducto);
			return ((ISingleResult<pa_S_TrazabilidadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_S_LibroReceta")]
		public ISingleResult<pa_S_LibroRecetaResult> pa_S_LibroReceta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_fechaIni, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_fechaFin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codProducto, p_fechaIni, p_fechaFin);
			return ((ISingleResult<pa_S_LibroRecetaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_S_KardexTrazabilidad")]
		public ISingleResult<pa_S_KardexTrazabilidadResult> pa_S_KardexTrazabilidad([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codigoTraza)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codProducto, p_codigoTraza);
			return ((ISingleResult<pa_S_KardexTrazabilidadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_S_OrdendeCompraTrazabilidad")]
		public ISingleResult<pa_S_OrdendeCompraTrazabilidadResult> pa_S_OrdendeCompraTrazabilidad([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codigoTraza)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codProducto, p_codigoTraza);
			return ((ISingleResult<pa_S_OrdendeCompraTrazabilidadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_S_OrdenDeDespachoTrazabilidad")]
		public ISingleResult<pa_S_OrdenDeDespachoTrazabilidadResult> pa_S_OrdenDeDespachoTrazabilidad([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codigoTraza)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codProducto, p_codigoTraza);
			return ((ISingleResult<pa_S_OrdenDeDespachoTrazabilidadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_S_LibroRecetaTrazabilidad")]
		public ISingleResult<pa_S_LibroRecetaTrazabilidadResult> pa_S_LibroRecetaTrazabilidad([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codigoTraza)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codProducto, p_codigoTraza);
			return ((ISingleResult<pa_S_LibroRecetaTrazabilidadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_S_HojaMermaTrazabilidad")]
		public ISingleResult<pa_S_HojaMermaTrazabilidadResult> pa_S_HojaMermaTrazabilidad([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codigoTraza)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codProducto, p_codigoTraza);
			return ((ISingleResult<pa_S_HojaMermaTrazabilidadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_S_InformeTrazabilidad")]
		public ISingleResult<pa_S_InformeTrazabilidadResult> pa_S_InformeTrazabilidad([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codigoInformeTrazabilidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codigoInformeTrazabilidad);
			return ((ISingleResult<pa_S_InformeTrazabilidadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_S_InformeVentaTrazabilidad")]
		public ISingleResult<pa_S_InformeVentaTrazabilidadResult> pa_S_InformeVentaTrazabilidad([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codigoTraza)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codProducto, p_codigoTraza);
			return ((ISingleResult<pa_S_InformeVentaTrazabilidadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_U_Procedimiento")]
		public int pa_U_Procedimiento([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codigoProcedimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_version, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> p_fechIniVigencia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> p_fechFinVigencia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_responsable, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_unidadPlazo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(250)")] string p_observaciones, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(250)")] string p_actividadProcedimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(250)")] string p_plazoActividad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codigoProcedimiento, p_version, p_fechIniVigencia, p_fechFinVigencia, p_responsable, p_unidadPlazo, p_observaciones, p_actividadProcedimiento, p_plazoActividad, tipo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_S_ProcedimientoById")]
		public ISingleResult<pa_S_ProcedimientoByIdResult> pa_S_ProcedimientoById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codProcedimiento)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codProcedimiento);
			return ((ISingleResult<pa_S_ProcedimientoByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Trazabilidad.pa_D_TrazabilidadDetalle")]
		public int pa_D_TrazabilidadDetalle([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codigoTraza)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codigoTraza);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class pa_S_KardexResult
	{
		
		private string _codigoProducto;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _ingreso;
		
		private string _numeroKardex;
		
		private string _observaciones;
		
		private string _saldos;
		
		private string _salidas;
		
		public pa_S_KardexResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProducto", DbType="VarChar(10)")]
		public string codigoProducto
		{
			get
			{
				return this._codigoProducto;
			}
			set
			{
				if ((this._codigoProducto != value))
				{
					this._codigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ingreso", DbType="VarChar(10)")]
		public string ingreso
		{
			get
			{
				return this._ingreso;
			}
			set
			{
				if ((this._ingreso != value))
				{
					this._ingreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroKardex", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string numeroKardex
		{
			get
			{
				return this._numeroKardex;
			}
			set
			{
				if ((this._numeroKardex != value))
				{
					this._numeroKardex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observaciones", DbType="VarChar(255)")]
		public string observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				if ((this._observaciones != value))
				{
					this._observaciones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldos", DbType="VarChar(10)")]
		public string saldos
		{
			get
			{
				return this._saldos;
			}
			set
			{
				if ((this._saldos != value))
				{
					this._saldos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salidas", DbType="VarChar(10)")]
		public string salidas
		{
			get
			{
				return this._salidas;
			}
			set
			{
				if ((this._salidas != value))
				{
					this._salidas = value;
				}
			}
		}
	}
	
	public partial class pa_S_OrdendeCompraResult
	{
		
		private string _cantidad;
		
		private string _codigoCompra;
		
		private string _codigoProducto;
		
		private string _costo;
		
		private System.Nullable<System.DateTime> _fechaCompra;
		
		private string _nombreProducto;
		
		private string _nombreProveedor;
		
		public pa_S_OrdendeCompraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="VarChar(10)")]
		public string cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this._cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoCompra", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string codigoCompra
		{
			get
			{
				return this._codigoCompra;
			}
			set
			{
				if ((this._codigoCompra != value))
				{
					this._codigoCompra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProducto", DbType="VarChar(10)")]
		public string codigoProducto
		{
			get
			{
				return this._codigoProducto;
			}
			set
			{
				if ((this._codigoProducto != value))
				{
					this._codigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costo", DbType="VarChar(10)")]
		public string costo
		{
			get
			{
				return this._costo;
			}
			set
			{
				if ((this._costo != value))
				{
					this._costo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaCompra", DbType="Date")]
		public System.Nullable<System.DateTime> fechaCompra
		{
			get
			{
				return this._fechaCompra;
			}
			set
			{
				if ((this._fechaCompra != value))
				{
					this._fechaCompra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreProducto", DbType="VarChar(10)")]
		public string nombreProducto
		{
			get
			{
				return this._nombreProducto;
			}
			set
			{
				if ((this._nombreProducto != value))
				{
					this._nombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreProveedor", DbType="VarChar(10)")]
		public string nombreProveedor
		{
			get
			{
				return this._nombreProveedor;
			}
			set
			{
				if ((this._nombreProveedor != value))
				{
					this._nombreProveedor = value;
				}
			}
		}
	}
	
	public partial class pa_S_OrdenDeDespachoResult
	{
		
		private string _codigoProducto;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _numeroOrden;
		
		private string _observaciones;
		
		private string _pesoTotal;
		
		private string _totalPedidos;
		
		public pa_S_OrdenDeDespachoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProducto", DbType="VarChar(10)")]
		public string codigoProducto
		{
			get
			{
				return this._codigoProducto;
			}
			set
			{
				if ((this._codigoProducto != value))
				{
					this._codigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroOrden", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string numeroOrden
		{
			get
			{
				return this._numeroOrden;
			}
			set
			{
				if ((this._numeroOrden != value))
				{
					this._numeroOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observaciones", DbType="VarChar(255)")]
		public string observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				if ((this._observaciones != value))
				{
					this._observaciones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pesoTotal", DbType="VarChar(10)")]
		public string pesoTotal
		{
			get
			{
				return this._pesoTotal;
			}
			set
			{
				if ((this._pesoTotal != value))
				{
					this._pesoTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalPedidos", DbType="VarChar(10)")]
		public string totalPedidos
		{
			get
			{
				return this._totalPedidos;
			}
			set
			{
				if ((this._totalPedidos != value))
				{
					this._totalPedidos = value;
				}
			}
		}
	}
	
	public partial class pa_S_HojaMermaResult
	{
		
		private string _codigoProducto;
		
		private string _cantidadInsumo;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _motivo;
		
		private string _numeroHojaMerma;
		
		public pa_S_HojaMermaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProducto", DbType="VarChar(10)")]
		public string codigoProducto
		{
			get
			{
				return this._codigoProducto;
			}
			set
			{
				if ((this._codigoProducto != value))
				{
					this._codigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidadInsumo", DbType="VarChar(10)")]
		public string cantidadInsumo
		{
			get
			{
				return this._cantidadInsumo;
			}
			set
			{
				if ((this._cantidadInsumo != value))
				{
					this._cantidadInsumo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motivo", DbType="VarChar(50)")]
		public string motivo
		{
			get
			{
				return this._motivo;
			}
			set
			{
				if ((this._motivo != value))
				{
					this._motivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroHojaMerma", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string numeroHojaMerma
		{
			get
			{
				return this._numeroHojaMerma;
			}
			set
			{
				if ((this._numeroHojaMerma != value))
				{
					this._numeroHojaMerma = value;
				}
			}
		}
	}
	
	public partial class pa_S_InformeVentaResult
	{
		
		private string _codigoVenta;
		
		private System.Nullable<System.DateTime> _fechaVenta;
		
		private string _nombreProducto;
		
		private string _cantidad;
		
		private string _codigoProducto;
		
		private string _precio;
		
		private string _nombreCliente;
		
		public pa_S_InformeVentaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoVenta", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string codigoVenta
		{
			get
			{
				return this._codigoVenta;
			}
			set
			{
				if ((this._codigoVenta != value))
				{
					this._codigoVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaVenta", DbType="Date")]
		public System.Nullable<System.DateTime> fechaVenta
		{
			get
			{
				return this._fechaVenta;
			}
			set
			{
				if ((this._fechaVenta != value))
				{
					this._fechaVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreProducto", DbType="VarChar(10)")]
		public string nombreProducto
		{
			get
			{
				return this._nombreProducto;
			}
			set
			{
				if ((this._nombreProducto != value))
				{
					this._nombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="VarChar(10)")]
		public string cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this._cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProducto", DbType="VarChar(10)")]
		public string codigoProducto
		{
			get
			{
				return this._codigoProducto;
			}
			set
			{
				if ((this._codigoProducto != value))
				{
					this._codigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="VarChar(10)")]
		public string precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this._precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreCliente", DbType="VarChar(10)")]
		public string nombreCliente
		{
			get
			{
				return this._nombreCliente;
			}
			set
			{
				if ((this._nombreCliente != value))
				{
					this._nombreCliente = value;
				}
			}
		}
	}
	
	public partial class pa_S_ProductoResult
	{
		
		private string _codigoProducto;
		
		private string _descripcion;
		
		private string _nombreProducto;
		
		private string _pesoProducto;
		
		private string _presentacion;
		
		private string _tipoProducto;
		
		public pa_S_ProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProducto", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string codigoProducto
		{
			get
			{
				return this._codigoProducto;
			}
			set
			{
				if ((this._codigoProducto != value))
				{
					this._codigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreProducto", DbType="VarChar(50)")]
		public string nombreProducto
		{
			get
			{
				return this._nombreProducto;
			}
			set
			{
				if ((this._nombreProducto != value))
				{
					this._nombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pesoProducto", DbType="VarChar(10)")]
		public string pesoProducto
		{
			get
			{
				return this._pesoProducto;
			}
			set
			{
				if ((this._pesoProducto != value))
				{
					this._pesoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_presentacion", DbType="VarChar(10)")]
		public string presentacion
		{
			get
			{
				return this._presentacion;
			}
			set
			{
				if ((this._presentacion != value))
				{
					this._presentacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoProducto", DbType="VarChar(50)")]
		public string tipoProducto
		{
			get
			{
				return this._tipoProducto;
			}
			set
			{
				if ((this._tipoProducto != value))
				{
					this._tipoProducto = value;
				}
			}
		}
	}
	
	public partial class pa_S_FichaTecnicaProductoFarmaciaResult
	{
		
		private string _codigoFichaTecProducto;
		
		private string _aprobar;
		
		private string _codigoFichaTecProveedor;
		
		private string _codigoProcedimiento;
		
		private string _descripcion;
		
		private string _etiquetado;
		
		private string _nombre;
		
		private string _posologia;
		
		private string _procedimiemtoDistribucion;
		
		private string _procedimientoAlmacen;
		
		private string _procedimientoVenta;
		
		private string _quimicoFarmaceutico;
		
		public pa_S_FichaTecnicaProductoFarmaciaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoFichaTecProducto", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string codigoFichaTecProducto
		{
			get
			{
				return this._codigoFichaTecProducto;
			}
			set
			{
				if ((this._codigoFichaTecProducto != value))
				{
					this._codigoFichaTecProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aprobar", DbType="VarChar(10)")]
		public string aprobar
		{
			get
			{
				return this._aprobar;
			}
			set
			{
				if ((this._aprobar != value))
				{
					this._aprobar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoFichaTecProveedor", DbType="VarChar(10)")]
		public string codigoFichaTecProveedor
		{
			get
			{
				return this._codigoFichaTecProveedor;
			}
			set
			{
				if ((this._codigoFichaTecProveedor != value))
				{
					this._codigoFichaTecProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProcedimiento", DbType="VarChar(10)")]
		public string codigoProcedimiento
		{
			get
			{
				return this._codigoProcedimiento;
			}
			set
			{
				if ((this._codigoProcedimiento != value))
				{
					this._codigoProcedimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(10)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etiquetado", DbType="VarChar(10)")]
		public string etiquetado
		{
			get
			{
				return this._etiquetado;
			}
			set
			{
				if ((this._etiquetado != value))
				{
					this._etiquetado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(10)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_posologia", DbType="VarChar(50)")]
		public string posologia
		{
			get
			{
				return this._posologia;
			}
			set
			{
				if ((this._posologia != value))
				{
					this._posologia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_procedimiemtoDistribucion", DbType="VarChar(255)")]
		public string procedimiemtoDistribucion
		{
			get
			{
				return this._procedimiemtoDistribucion;
			}
			set
			{
				if ((this._procedimiemtoDistribucion != value))
				{
					this._procedimiemtoDistribucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_procedimientoAlmacen", DbType="VarChar(255)")]
		public string procedimientoAlmacen
		{
			get
			{
				return this._procedimientoAlmacen;
			}
			set
			{
				if ((this._procedimientoAlmacen != value))
				{
					this._procedimientoAlmacen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_procedimientoVenta", DbType="VarChar(255)")]
		public string procedimientoVenta
		{
			get
			{
				return this._procedimientoVenta;
			}
			set
			{
				if ((this._procedimientoVenta != value))
				{
					this._procedimientoVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quimicoFarmaceutico", DbType="VarChar(10)")]
		public string quimicoFarmaceutico
		{
			get
			{
				return this._quimicoFarmaceutico;
			}
			set
			{
				if ((this._quimicoFarmaceutico != value))
				{
					this._quimicoFarmaceutico = value;
				}
			}
		}
	}
	
	public partial class pa_S_UsuarioTrazabilidadResult
	{
		
		private string _desLogin;
		
		public pa_S_UsuarioTrazabilidadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desLogin", DbType="VarChar(40)")]
		public string desLogin
		{
			get
			{
				return this._desLogin;
			}
			set
			{
				if ((this._desLogin != value))
				{
					this._desLogin = value;
				}
			}
		}
	}
	
	public partial class pa_S_ProcedimientoResult
	{
		
		private string _codigoProcedimiento;
		
		private string _version;
		
		private System.Nullable<System.DateTime> _fechIniVigencia;
		
		private System.Nullable<System.DateTime> _fechFinVigencia;
		
		private string _responsable;
		
		private string _unidadPlazo;
		
		private string _observaciones;
		
		private string _nombreProducto;
		
		private string _actividadProcedimiento;
		
		private string _plazoActividad;
		
		public pa_S_ProcedimientoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProcedimiento", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string codigoProcedimiento
		{
			get
			{
				return this._codigoProcedimiento;
			}
			set
			{
				if ((this._codigoProcedimiento != value))
				{
					this._codigoProcedimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_version", DbType="VarChar(10)")]
		public string version
		{
			get
			{
				return this._version;
			}
			set
			{
				if ((this._version != value))
				{
					this._version = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechIniVigencia", DbType="Date")]
		public System.Nullable<System.DateTime> fechIniVigencia
		{
			get
			{
				return this._fechIniVigencia;
			}
			set
			{
				if ((this._fechIniVigencia != value))
				{
					this._fechIniVigencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechFinVigencia", DbType="Date")]
		public System.Nullable<System.DateTime> fechFinVigencia
		{
			get
			{
				return this._fechFinVigencia;
			}
			set
			{
				if ((this._fechFinVigencia != value))
				{
					this._fechFinVigencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_responsable", DbType="VarChar(50)")]
		public string responsable
		{
			get
			{
				return this._responsable;
			}
			set
			{
				if ((this._responsable != value))
				{
					this._responsable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unidadPlazo", DbType="VarChar(10)")]
		public string unidadPlazo
		{
			get
			{
				return this._unidadPlazo;
			}
			set
			{
				if ((this._unidadPlazo != value))
				{
					this._unidadPlazo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observaciones", DbType="VarChar(250)")]
		public string observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				if ((this._observaciones != value))
				{
					this._observaciones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreProducto", DbType="VarChar(50)")]
		public string nombreProducto
		{
			get
			{
				return this._nombreProducto;
			}
			set
			{
				if ((this._nombreProducto != value))
				{
					this._nombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actividadProcedimiento", DbType="VarChar(250)")]
		public string actividadProcedimiento
		{
			get
			{
				return this._actividadProcedimiento;
			}
			set
			{
				if ((this._actividadProcedimiento != value))
				{
					this._actividadProcedimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plazoActividad", DbType="VarChar(250)")]
		public string plazoActividad
		{
			get
			{
				return this._plazoActividad;
			}
			set
			{
				if ((this._plazoActividad != value))
				{
					this._plazoActividad = value;
				}
			}
		}
	}
	
	public partial class pa_S_TrazabilidadResult
	{
		
		private string _codigoTraza;
		
		private System.Nullable<System.DateTime> _fechaTraza;
		
		private string _nombreProducto;
		
		private string _estado;
		
		private string _estadoinformetrazabilidad;
		
		public pa_S_TrazabilidadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoTraza", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string codigoTraza
		{
			get
			{
				return this._codigoTraza;
			}
			set
			{
				if ((this._codigoTraza != value))
				{
					this._codigoTraza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaTraza", DbType="Date")]
		public System.Nullable<System.DateTime> fechaTraza
		{
			get
			{
				return this._fechaTraza;
			}
			set
			{
				if ((this._fechaTraza != value))
				{
					this._fechaTraza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreProducto", DbType="VarChar(50)")]
		public string nombreProducto
		{
			get
			{
				return this._nombreProducto;
			}
			set
			{
				if ((this._nombreProducto != value))
				{
					this._nombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(50)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estadoinformetrazabilidad", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string estadoinformetrazabilidad
		{
			get
			{
				return this._estadoinformetrazabilidad;
			}
			set
			{
				if ((this._estadoinformetrazabilidad != value))
				{
					this._estadoinformetrazabilidad = value;
				}
			}
		}
	}
	
	public partial class pa_S_LibroRecetaResult
	{
		
		private string _codigoProducto;
		
		private System.Nullable<System.DateTime> _fechaProducto;
		
		private string _codigolibroreceta;
		
		private string _quimicoLaboratorista;
		
		public pa_S_LibroRecetaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProducto", DbType="VarChar(10)")]
		public string codigoProducto
		{
			get
			{
				return this._codigoProducto;
			}
			set
			{
				if ((this._codigoProducto != value))
				{
					this._codigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaProducto", DbType="Date")]
		public System.Nullable<System.DateTime> fechaProducto
		{
			get
			{
				return this._fechaProducto;
			}
			set
			{
				if ((this._fechaProducto != value))
				{
					this._fechaProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigolibroreceta", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string codigolibroreceta
		{
			get
			{
				return this._codigolibroreceta;
			}
			set
			{
				if ((this._codigolibroreceta != value))
				{
					this._codigolibroreceta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quimicoLaboratorista", DbType="VarChar(10)")]
		public string quimicoLaboratorista
		{
			get
			{
				return this._quimicoLaboratorista;
			}
			set
			{
				if ((this._quimicoLaboratorista != value))
				{
					this._quimicoLaboratorista = value;
				}
			}
		}
	}
	
	public partial class pa_S_KardexTrazabilidadResult
	{
		
		private string _codigoProducto;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _ingreso;
		
		private string _numeroKardex;
		
		private string _observaciones;
		
		private string _saldos;
		
		private string _salidas;
		
		public pa_S_KardexTrazabilidadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProducto", DbType="VarChar(10)")]
		public string codigoProducto
		{
			get
			{
				return this._codigoProducto;
			}
			set
			{
				if ((this._codigoProducto != value))
				{
					this._codigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ingreso", DbType="VarChar(10)")]
		public string ingreso
		{
			get
			{
				return this._ingreso;
			}
			set
			{
				if ((this._ingreso != value))
				{
					this._ingreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroKardex", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string numeroKardex
		{
			get
			{
				return this._numeroKardex;
			}
			set
			{
				if ((this._numeroKardex != value))
				{
					this._numeroKardex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observaciones", DbType="VarChar(255)")]
		public string observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				if ((this._observaciones != value))
				{
					this._observaciones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldos", DbType="VarChar(10)")]
		public string saldos
		{
			get
			{
				return this._saldos;
			}
			set
			{
				if ((this._saldos != value))
				{
					this._saldos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salidas", DbType="VarChar(10)")]
		public string salidas
		{
			get
			{
				return this._salidas;
			}
			set
			{
				if ((this._salidas != value))
				{
					this._salidas = value;
				}
			}
		}
	}
	
	public partial class pa_S_OrdendeCompraTrazabilidadResult
	{
		
		private string _cantidad;
		
		private string _codigoCompra;
		
		private string _codigoProducto;
		
		private string _costo;
		
		private System.Nullable<System.DateTime> _fechaCompra;
		
		private string _nombreProducto;
		
		private string _nombreProveedor;
		
		public pa_S_OrdendeCompraTrazabilidadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="VarChar(10)")]
		public string cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this._cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoCompra", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string codigoCompra
		{
			get
			{
				return this._codigoCompra;
			}
			set
			{
				if ((this._codigoCompra != value))
				{
					this._codigoCompra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProducto", DbType="VarChar(10)")]
		public string codigoProducto
		{
			get
			{
				return this._codigoProducto;
			}
			set
			{
				if ((this._codigoProducto != value))
				{
					this._codigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costo", DbType="VarChar(10)")]
		public string costo
		{
			get
			{
				return this._costo;
			}
			set
			{
				if ((this._costo != value))
				{
					this._costo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaCompra", DbType="Date")]
		public System.Nullable<System.DateTime> fechaCompra
		{
			get
			{
				return this._fechaCompra;
			}
			set
			{
				if ((this._fechaCompra != value))
				{
					this._fechaCompra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreProducto", DbType="VarChar(10)")]
		public string nombreProducto
		{
			get
			{
				return this._nombreProducto;
			}
			set
			{
				if ((this._nombreProducto != value))
				{
					this._nombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreProveedor", DbType="VarChar(10)")]
		public string nombreProveedor
		{
			get
			{
				return this._nombreProveedor;
			}
			set
			{
				if ((this._nombreProveedor != value))
				{
					this._nombreProveedor = value;
				}
			}
		}
	}
	
	public partial class pa_S_OrdenDeDespachoTrazabilidadResult
	{
		
		private string _codigoProducto;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _numeroOrden;
		
		private string _observaciones;
		
		private string _pesoTotal;
		
		private string _totalPedidos;
		
		public pa_S_OrdenDeDespachoTrazabilidadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProducto", DbType="VarChar(10)")]
		public string codigoProducto
		{
			get
			{
				return this._codigoProducto;
			}
			set
			{
				if ((this._codigoProducto != value))
				{
					this._codigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroOrden", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string numeroOrden
		{
			get
			{
				return this._numeroOrden;
			}
			set
			{
				if ((this._numeroOrden != value))
				{
					this._numeroOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observaciones", DbType="VarChar(255)")]
		public string observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				if ((this._observaciones != value))
				{
					this._observaciones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pesoTotal", DbType="VarChar(10)")]
		public string pesoTotal
		{
			get
			{
				return this._pesoTotal;
			}
			set
			{
				if ((this._pesoTotal != value))
				{
					this._pesoTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalPedidos", DbType="VarChar(10)")]
		public string totalPedidos
		{
			get
			{
				return this._totalPedidos;
			}
			set
			{
				if ((this._totalPedidos != value))
				{
					this._totalPedidos = value;
				}
			}
		}
	}
	
	public partial class pa_S_LibroRecetaTrazabilidadResult
	{
		
		private string _codigoProducto;
		
		private System.Nullable<System.DateTime> _fechaProducto;
		
		private string _codigolibroreceta;
		
		private string _quimicoLaboratorista;
		
		public pa_S_LibroRecetaTrazabilidadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProducto", DbType="VarChar(10)")]
		public string codigoProducto
		{
			get
			{
				return this._codigoProducto;
			}
			set
			{
				if ((this._codigoProducto != value))
				{
					this._codigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaProducto", DbType="Date")]
		public System.Nullable<System.DateTime> fechaProducto
		{
			get
			{
				return this._fechaProducto;
			}
			set
			{
				if ((this._fechaProducto != value))
				{
					this._fechaProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigolibroreceta", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string codigolibroreceta
		{
			get
			{
				return this._codigolibroreceta;
			}
			set
			{
				if ((this._codigolibroreceta != value))
				{
					this._codigolibroreceta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quimicoLaboratorista", DbType="VarChar(10)")]
		public string quimicoLaboratorista
		{
			get
			{
				return this._quimicoLaboratorista;
			}
			set
			{
				if ((this._quimicoLaboratorista != value))
				{
					this._quimicoLaboratorista = value;
				}
			}
		}
	}
	
	public partial class pa_S_HojaMermaTrazabilidadResult
	{
		
		private string _codigoProducto;
		
		private string _cantidadInsumo;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _motivo;
		
		private string _numeroHojaMerma;
		
		public pa_S_HojaMermaTrazabilidadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProducto", DbType="VarChar(10)")]
		public string codigoProducto
		{
			get
			{
				return this._codigoProducto;
			}
			set
			{
				if ((this._codigoProducto != value))
				{
					this._codigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidadInsumo", DbType="VarChar(10)")]
		public string cantidadInsumo
		{
			get
			{
				return this._cantidadInsumo;
			}
			set
			{
				if ((this._cantidadInsumo != value))
				{
					this._cantidadInsumo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_motivo", DbType="VarChar(50)")]
		public string motivo
		{
			get
			{
				return this._motivo;
			}
			set
			{
				if ((this._motivo != value))
				{
					this._motivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroHojaMerma", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string numeroHojaMerma
		{
			get
			{
				return this._numeroHojaMerma;
			}
			set
			{
				if ((this._numeroHojaMerma != value))
				{
					this._numeroHojaMerma = value;
				}
			}
		}
	}
	
	public partial class pa_S_InformeTrazabilidadResult
	{
		
		private string _codigoTraza;
		
		private string _nombreProducto;
		
		private string _detalleAnalisis;
		
		private string _fechaTrazastring;
		
		private string _codigoInformeTrazabilidad;
		
		private string _estado;
		
		public pa_S_InformeTrazabilidadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoTraza", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string codigoTraza
		{
			get
			{
				return this._codigoTraza;
			}
			set
			{
				if ((this._codigoTraza != value))
				{
					this._codigoTraza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreProducto", DbType="VarChar(50)")]
		public string nombreProducto
		{
			get
			{
				return this._nombreProducto;
			}
			set
			{
				if ((this._nombreProducto != value))
				{
					this._nombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detalleAnalisis", DbType="VarChar(255)")]
		public string detalleAnalisis
		{
			get
			{
				return this._detalleAnalisis;
			}
			set
			{
				if ((this._detalleAnalisis != value))
				{
					this._detalleAnalisis = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaTrazastring", DbType="VarChar(8)")]
		public string fechaTrazastring
		{
			get
			{
				return this._fechaTrazastring;
			}
			set
			{
				if ((this._fechaTrazastring != value))
				{
					this._fechaTrazastring = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoInformeTrazabilidad", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string codigoInformeTrazabilidad
		{
			get
			{
				return this._codigoInformeTrazabilidad;
			}
			set
			{
				if ((this._codigoInformeTrazabilidad != value))
				{
					this._codigoInformeTrazabilidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(15)")]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
	}
	
	public partial class pa_S_InformeVentaTrazabilidadResult
	{
		
		private string _codigoVenta;
		
		private System.Nullable<System.DateTime> _fechaVenta;
		
		private string _nombreProducto;
		
		private string _cantidad;
		
		private string _codigoProducto;
		
		private string _precio;
		
		private string _nombreCliente;
		
		public pa_S_InformeVentaTrazabilidadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoVenta", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string codigoVenta
		{
			get
			{
				return this._codigoVenta;
			}
			set
			{
				if ((this._codigoVenta != value))
				{
					this._codigoVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaVenta", DbType="Date")]
		public System.Nullable<System.DateTime> fechaVenta
		{
			get
			{
				return this._fechaVenta;
			}
			set
			{
				if ((this._fechaVenta != value))
				{
					this._fechaVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreProducto", DbType="VarChar(10)")]
		public string nombreProducto
		{
			get
			{
				return this._nombreProducto;
			}
			set
			{
				if ((this._nombreProducto != value))
				{
					this._nombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="VarChar(10)")]
		public string cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this._cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProducto", DbType="VarChar(10)")]
		public string codigoProducto
		{
			get
			{
				return this._codigoProducto;
			}
			set
			{
				if ((this._codigoProducto != value))
				{
					this._codigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio", DbType="VarChar(10)")]
		public string precio
		{
			get
			{
				return this._precio;
			}
			set
			{
				if ((this._precio != value))
				{
					this._precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreCliente", DbType="VarChar(10)")]
		public string nombreCliente
		{
			get
			{
				return this._nombreCliente;
			}
			set
			{
				if ((this._nombreCliente != value))
				{
					this._nombreCliente = value;
				}
			}
		}
	}
	
	public partial class pa_S_ProcedimientoByIdResult
	{
		
		private string _codigoProcedimiento;
		
		private string _version;
		
		private System.Nullable<System.DateTime> _fechIniVigencia;
		
		private System.Nullable<System.DateTime> _fechFinVigencia;
		
		private string _responsable;
		
		private string _unidadPlazo;
		
		private string _observaciones;
		
		private string _actividadProcedimiento;
		
		private string _plazoActividad;
		
		private string _tipo;
		
		public pa_S_ProcedimientoByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProcedimiento", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string codigoProcedimiento
		{
			get
			{
				return this._codigoProcedimiento;
			}
			set
			{
				if ((this._codigoProcedimiento != value))
				{
					this._codigoProcedimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_version", DbType="VarChar(10)")]
		public string version
		{
			get
			{
				return this._version;
			}
			set
			{
				if ((this._version != value))
				{
					this._version = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechIniVigencia", DbType="Date")]
		public System.Nullable<System.DateTime> fechIniVigencia
		{
			get
			{
				return this._fechIniVigencia;
			}
			set
			{
				if ((this._fechIniVigencia != value))
				{
					this._fechIniVigencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechFinVigencia", DbType="Date")]
		public System.Nullable<System.DateTime> fechFinVigencia
		{
			get
			{
				return this._fechFinVigencia;
			}
			set
			{
				if ((this._fechFinVigencia != value))
				{
					this._fechFinVigencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_responsable", DbType="VarChar(50)")]
		public string responsable
		{
			get
			{
				return this._responsable;
			}
			set
			{
				if ((this._responsable != value))
				{
					this._responsable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unidadPlazo", DbType="VarChar(10)")]
		public string unidadPlazo
		{
			get
			{
				return this._unidadPlazo;
			}
			set
			{
				if ((this._unidadPlazo != value))
				{
					this._unidadPlazo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observaciones", DbType="VarChar(250)")]
		public string observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				if ((this._observaciones != value))
				{
					this._observaciones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actividadProcedimiento", DbType="VarChar(250)")]
		public string actividadProcedimiento
		{
			get
			{
				return this._actividadProcedimiento;
			}
			set
			{
				if ((this._actividadProcedimiento != value))
				{
					this._actividadProcedimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plazoActividad", DbType="VarChar(250)")]
		public string plazoActividad
		{
			get
			{
				return this._plazoActividad;
			}
			set
			{
				if ((this._plazoActividad != value))
				{
					this._plazoActividad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(10)")]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this._tipo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
