<?xml version="1.0" encoding="utf-8"?><Database Name="BD_ByS" Class="_DBMLPresupuestoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=WALTER-PC\AAAAAAAA;Initial Catalog=BD_ByS;Integrated Security=True" SettingsObjectName="ByS.Presupuesto.Data.Properties.Settings" SettingsPropertyName="BD_BySConnectionString4" Provider="System.Data.SqlClient" />
  <Function Name="Presupuesto.pa_D_Gasto" Method="pa_D_Gasto">
    <Parameter Name="p_codGasto" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_segUsuarioElimina" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="p_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Presupuesto.pa_U_SolicitudDeta" Method="pa_U_SolicitudDeta">
    <Parameter Name="p_codSolicitudDeta" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codSolicitud" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codPlantillaDeta" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_cntCantidad" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="p_gloDescripcion" Type="System.String" DbType="VarChar(120)" />
    <Parameter Name="p_segUsuarioEdita" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="p_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Presupuesto.pa_D_PlantillaDeta" Method="pa_D_PlantillaDeta">
    <Parameter Name="p_codPlantillaDeta" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_segUsuarioEdita" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="p_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Presupuesto.pa_D_Solicitud" Method="pa_D_Solicitud">
    <Parameter Name="p_codSolicitud" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_segUsuarioElimina" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="p_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Presupuesto.pa_D_SolicitudDeta" Method="pa_D_SolicitudDeta">
    <Parameter Name="p_codSolicitudDeta" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_segUsuarioElimina" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="p_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Presupuesto.pa_I_Gasto" Method="pa_I_Gasto">
    <Parameter Name="p_codGasto" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="p_codPlantillaDeta" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_monTotal" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="p_cntCantidad" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="p_numDocumento" Type="System.String" DbType="NVarChar(16)" />
    <Parameter Name="p_gloObservacion" Type="System.String" DbType="NVarChar(120)" />
    <Parameter Name="p_fecGasto" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="p_codEmpleadoResp" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_segUsuarioCrea" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="p_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Presupuesto.pa_I_PlantillaDeta" Method="pa_I_PlantillaDeta">
    <Parameter Name="p_codPlantillaDeta" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="p_codPlantilla" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_gloDescripcion" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="p_monEstimado" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="p_cntCantidad" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="p_fecEjecucion" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="p_indPlantilla" Type="System.String" DbType="NVarChar(1)" />
    <Parameter Name="p_codPartida" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_segUsuarioCrea" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="p_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Presupuesto.pa_I_PlantillaDetaRefer" Method="pa_I_PlantillaDetaRefer">
    <Parameter Name="p_codPlantillaDeta" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="p_codPlantillaDetaRefer" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codPlantilla" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_segUsuarioCrea" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="p_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Presupuesto.pa_I_Solicitud" Method="pa_I_Solicitud">
    <Parameter Name="p_codSolicitud" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="p_gloObservacion" Type="System.String" DbType="VarChar(120)" />
    <Parameter Name="p_fecSolicituda" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="p_indTipo" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="p_fecLimite" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="p_codEmpleadoGenera" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codPresupuesto" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codRegEstado" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_segUsuarioCrea" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="p_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Presupuesto.pa_I_SolicitudDeta" Method="pa_I_SolicitudDeta">
    <Parameter Name="p_codSolicitudDeta" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="p_codSolicitud" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codPlantillaDeta" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_cntCantidad" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="p_gloDescripcion" Type="System.String" DbType="VarChar(120)" />
    <Parameter Name="p_segUsuarioCrea" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="p_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Presupuesto.pa_S_Gasto" Method="pa_S_Gasto">
    <Parameter Name="p_codGasto" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codPlantillaDeta" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codArea" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_anio" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_S_GastoResult">
      <Column Name="codGasto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codPlantillaDeta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="monTotal" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="cntCantidad" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="numDocumento" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="gloObservacion" Type="System.String" DbType="NVarChar(120)" CanBeNull="true" />
      <Column Name="fecGasto" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="codEmpleadoResp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codEmpleadoRespNombre" Type="System.String" DbType="VarChar(81)" CanBeNull="true" />
      <Column Name="segUsuarioCrea" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioEdita" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="segFechaCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segMaquinaOrigen" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="codArea" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codAreaNombre" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="codPresupuesto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codPresupuestoNombre" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Presupuesto.pa_S_GastoPagina" Method="pa_S_GastoPagina">
    <Parameter Name="p_NumPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_TamPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_OrdenPor" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="p_OrdenTipo" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="p_codGasto" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codPlantillaDeta" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codArea" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_anio" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_S_GastoPaginaResult">
      <Column Name="codGasto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codPlantillaDeta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="monTotal" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="cntCantidad" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="numDocumento" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="gloObservacion" Type="System.String" DbType="NVarChar(120)" CanBeNull="true" />
      <Column Name="fecGasto" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="codEmpleadoResp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codEmpleadoRespNombre" Type="System.String" DbType="VarChar(81)" CanBeNull="true" />
      <Column Name="segUsuarioCrea" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioEdita" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="segFechaCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segMaquinaOrigen" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="codArea" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codAreaNombre" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="codPresupuesto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codPresupuestoNombre" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TOTALROWS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ROWNUM" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Presupuesto.pa_S_Partida" Method="pa_S_Partida">
    <ElementType Name="pa_S_PartidaResult">
      <Column Name="codPartida" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="desNombre" Type="System.String" DbType="NVarChar(71)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Presupuesto.pa_S_Plantilla" Method="pa_S_Plantilla">
    <Parameter Name="p_codPlantilla" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_anio" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codArea" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_S_PlantillaResult">
      <Column Name="codPlantilla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="numPlantilla" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="nombrePresupuesto" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="numAnio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecCierre" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="codAreaNombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="desEmpleadoActual" Type="System.String" DbType="VarChar(82) NOT NULL" CanBeNull="false" />
      <Column Name="codCargoNombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="desEmpleadoElabora" Type="System.String" DbType="VarChar(82) NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segUsuarioEdita" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="segFechaCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioCrea" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="monMaximo" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="numDiasExtemporaneo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EstadoPlantilla" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="monEstimadoTotalxArea" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Presupuesto.pa_S_PlantillaDeta" Method="pa_S_PlantillaDeta">
    <Parameter Name="p_codPlantillaDeta" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_anio" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codArea" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codRegEstado" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_S_PlantillaDetaResult">
      <Column Name="codPlantillaDeta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codPlantilla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codEmpleadoAprueba" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codEmpleadoApruebaNombre" Type="System.String" DbType="VarChar(82)" CanBeNull="true" />
      <Column Name="gloDescripcion" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="monEstimado" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="cntCantidad" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="codRegEstado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codRegEstadoNombre" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="fecEjecucion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="codEmpleadoRespon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codEmpleadoResponRespon" Type="System.String" DbType="VarChar(82)" CanBeNull="true" />
      <Column Name="indPlantilla" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="indPlantillaTipo" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="codPartida" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="numPartida" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioCrea" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioEdita" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="segFechaCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segMaquinaOrigen" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="codPartidaNombre" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="codNumero" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="codArea" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codAreaNombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Presupuesto.pa_S_PlantillaDetaPagina" Method="pa_S_PlantillaDetaPagina">
    <Parameter Name="p_NumPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_TamPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_OrdenPor" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="p_OrdenTipo" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="p_anio" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codArea" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codRegEstado" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_S_PlantillaDetaPaginaResult">
      <Column Name="codPlantillaDeta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codPlantilla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codEmpleadoAprueba" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codEmpleadoApruebaNombre" Type="System.String" DbType="VarChar(82)" CanBeNull="true" />
      <Column Name="gloDescripcion" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="monEstimado" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="cntCantidad" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="codRegEstado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codRegEstadoNombre" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="fecEjecucion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="codEmpleadoRespon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codEmpleadoResponRespon" Type="System.String" DbType="VarChar(82)" CanBeNull="true" />
      <Column Name="indPlantilla" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="indPlantillaTipo" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="codPartida" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="numPartida" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioCrea" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioEdita" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="segFechaCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segMaquinaOrigen" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="codPartidaNombre" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="codNumero" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="codArea" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codAreaNombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="TOTALROWS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ROWNUM" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Presupuesto.pa_S_PlantillaDetaPendPagina" Method="pa_S_PlantillaDetaPendPagina">
    <Parameter Name="p_NumPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_TamPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_OrdenPor" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="p_OrdenTipo" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="p_anio" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codArea" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codRegEstado" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_S_PlantillaDetaPendPaginaResult">
      <Column Name="codPlantillaDeta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codPlantilla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codEmpleadoAprueba" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codEmpleadoApruebaNombre" Type="System.String" DbType="VarChar(82)" CanBeNull="true" />
      <Column Name="gloDescripcion" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="monEstimado" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="cntCantidad" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="codRegEstado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codRegEstadoNombre" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="fecEjecucion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="codEmpleadoRespon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codEmpleadoResponRespon" Type="System.String" DbType="VarChar(82)" CanBeNull="true" />
      <Column Name="indPlantilla" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="indPlantillaTipo" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="codPartida" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="numPartida" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioCrea" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioEdita" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="segFechaCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segMaquinaOrigen" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="codPartidaNombre" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="codNumero" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="codArea" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codAreaNombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="TOTALROWS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ROWNUM" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Presupuesto.pa_S_Presupuesto" Method="pa_S_Presupuesto">
    <Parameter Name="p_numAnio" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_S_PresupuestoResult">
      <Column Name="codPresupuesto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="desNombre" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="numAnio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecInicio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fecCierre" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="codRegEstado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioCrea" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioEdita" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="segFechaCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segMaquinaOrigen" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="indEliminado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="monTotalPresupuesto" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="monTotalSolicitado" Type="System.Decimal" DbType="Decimal(38,4)" CanBeNull="true" />
      <Column Name="monTotalGastado" Type="System.Decimal" DbType="Decimal(38,4)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Presupuesto.pa_S_Solicitud" Method="pa_S_Solicitud">
    <Parameter Name="p_codSolicitud" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_numSolicitud" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="p_fecSolicitadaIni" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="p_fecSolicitadaFin" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="p_codRegEstado" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codPresupuesto" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codArea" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_indTipo" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="pa_S_SolicitudResult">
      <Column Name="codSolicitud" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="numSolicitud" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="gloObservacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="fecSolicitada" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="indTipo" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="fecLimite" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="codEmpleadoGenera" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codEmpleadoGeneraNombre" Type="System.String" DbType="VarChar(82) NOT NULL" CanBeNull="false" />
      <Column Name="codEmpleadoAprueba" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codEmpleadoApruebaNombre" Type="System.String" DbType="VarChar(82)" CanBeNull="true" />
      <Column Name="codPresupuesto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codPresupuestoNombre" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="codRegEstado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codRegEstadoNombre" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="segUsuarioCrea" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioEdita" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="segFechaCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segMaquinaOrigen" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="codArea" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codAreaNombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Presupuesto.pa_S_SolicitudDeta" Method="pa_S_SolicitudDeta">
    <Parameter Name="p_codSolicitudDeta" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codSolicitud" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codPlantillaDeta" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codRegEstado" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codPresupuesto" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_S_SolicitudDetaResult">
      <Column Name="codSolicitudDeta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codSolicitud" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codPlantillaDeta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codPlantillaDetaDescri" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="fecEjecucion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="cntCantidad" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="gloDescripcion" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioCrea" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioEdita" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="segFechaCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segMaquinaOrigen" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="codEmpleadoAprueba" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codEmpleadoApruebaNombre" Type="System.String" DbType="VarChar(82)" CanBeNull="true" />
      <Column Name="cntCantidadPlantilla" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="numPartida" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="monEstimado" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="codPartida" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codPartidaNombre" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="gloDescripcionOrig" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Presupuesto.pa_S_SolicitudDetaPagina" Method="pa_S_SolicitudDetaPagina">
    <Parameter Name="p_NumPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_TamPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_OrdenPor" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="p_OrdenTipo" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="p_codSolicitudDeta" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codSolicitud" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codPlantillaDeta" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codRegEstado" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codPresupuesto" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_S_SolicitudDetaPaginaResult">
      <Column Name="codSolicitudDeta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codSolicitud" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codPlantillaDeta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codPlantillaDetaDescri" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="fecEjecucion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="cntCantidad" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="gloDescripcion" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioCrea" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioEdita" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="segFechaCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segMaquinaOrigen" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="codEmpleadoAprueba" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codEmpleadoApruebaNombre" Type="System.String" DbType="VarChar(82)" CanBeNull="true" />
      <Column Name="cntCantidadPlantilla" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="numPartida" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="monEstimado" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="codPartida" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codPartidaNombre" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="gloDescripcionOrig" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="TOTALROWS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ROWNUM" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Presupuesto.pa_S_SolicitudPagina" Method="pa_S_SolicitudPagina">
    <Parameter Name="p_NumPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_TamPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_OrdenPor" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="p_OrdenTipo" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="p_codSolicitud" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_numSolicitud" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="p_fecSolicitadaIni" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="p_fecSolicitadaFin" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="p_codRegEstado" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codPresupuesto" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codArea" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_indTipo" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="pa_S_SolicitudPaginaResult">
      <Column Name="codSolicitud" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="numSolicitud" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="gloObservacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="fecSolicitada" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="indTipo" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="fecLimite" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="codEmpleadoGenera" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codEmpleadoGeneraNombre" Type="System.String" DbType="VarChar(82) NOT NULL" CanBeNull="false" />
      <Column Name="codEmpleadoAprueba" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codEmpleadoApruebaNombre" Type="System.String" DbType="VarChar(82)" CanBeNull="true" />
      <Column Name="codPresupuesto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codPresupuestoNombre" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="codRegEstado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codRegEstadoNombre" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="segUsuarioCrea" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioEdita" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="segFechaCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segMaquinaOrigen" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="codArea" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codAreaNombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="TOTALROWS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ROWNUM" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Presupuesto.pa_U_Gasto" Method="pa_U_Gasto">
    <Parameter Name="p_codGasto" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_monTotal" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="p_cntCantidad" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="p_numDocumento" Type="System.String" DbType="NVarChar(16)" />
    <Parameter Name="p_gloObservacion" Type="System.String" DbType="NVarChar(120)" />
    <Parameter Name="p_fecGasto" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="p_codEmpleadoResp" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_segUsuarioEdita" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="p_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Presupuesto.pa_U_Plantilla_Estado" Method="pa_U_Plantilla_Estado">
    <Parameter Name="p_codPlantilla" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codRegEstado" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_segUsuarioEdita" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="p_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Presupuesto.pa_U_PlantillaDeta" Method="pa_U_PlantillaDeta">
    <Parameter Name="p_codPlantillaDeta" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_gloDescripcion" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="p_monEstimado" Type="System.Decimal" DbType="Decimal(12,2)" />
    <Parameter Name="p_cntCantidad" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="p_fecEjecucion" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="p_codPartida" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_segUsuarioEdita" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="p_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Presupuesto.pa_U_PlantillaDetaAprob" Method="pa_U_PlantillaDetaAprob">
    <Parameter Name="p_codPlantillaDeta" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codEmpleadoAprueba" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_segUsuarioEdita" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="p_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Presupuesto.pa_U_Solicitud" Method="pa_U_Solicitud">
    <Parameter Name="p_codSolicitud" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_gloObservacion" Type="System.String" DbType="VarChar(120)" />
    <Parameter Name="p_fecSolicitada" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="p_indTipo" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="p_fecLimite" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="p_codEmpleadoGenera" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codPresupuesto" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codRegEstado" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_segUsuarioEdita" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="p_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Presupuesto.pa_S_InformeSeguimiento" Method="pa_S_InformeSeguimiento">
    <Parameter Name="p_NumPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_TamPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_OrdenPor" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="p_OrdenTipo" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="p_anio" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codArea" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_codRegEstado" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_mesini" Type="System.Int32" DbType="Int" />
    <Parameter Name="p_mesfin" Type="System.Int32" DbType="Int" />
    <ElementType Name="pa_S_InformeSeguimientoResult">
      <Column Name="codPlantillaDeta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codPlantilla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codEmpleadoAprueba" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codEmpleadoResponNombre" Type="System.String" DbType="VarChar(82)" CanBeNull="true" />
      <Column Name="gloDescripcion" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="monEstimado" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="cntCantidad" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="codRegEstado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codRegEstadoNombre" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="fecEjecucion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="codEmpleadoRespon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="codEmpleadoResponRespon" Type="System.String" DbType="VarChar(82)" CanBeNull="true" />
      <Column Name="indPlantilla" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="indPlantillaTipo" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="codPartida" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="numPartida" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioCrea" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuarioEdita" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="segFechaCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segMaquinaOrigen" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="codPartidaNombre" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="codNumero" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="codArea" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codAreaNombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="TOTALROWS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ROWNUM" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>