#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByS.Presupuesto.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_ByS")]
	public partial class _DBMLPresupuestoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public _DBMLPresupuestoDataContext() : 
				base(global::ByS.Presupuesto.Data.Properties.Settings.Default.BD_BySConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public _DBMLPresupuestoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _DBMLPresupuestoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _DBMLPresupuestoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _DBMLPresupuestoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Presupuesto.pa_D_Gasto")]
		public int pa_D_Gasto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codGasto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segUsuarioElimina, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segMaquinaOrigen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codGasto, p_segUsuarioElimina, p_segMaquinaOrigen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="RecursosHumanos.pa_S_EmpleadoLogin")]
		public ISingleResult<pa_S_EmpleadoLoginResult> pa_S_EmpleadoLogin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_desLogin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_desLogin);
			return ((ISingleResult<pa_S_EmpleadoLoginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Presupuesto.pa_D_PlantillaDeta")]
		public int pa_D_PlantillaDeta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codPlantillaDeta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segUsuarioEdita, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segMaquinaOrigen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codPlantillaDeta, p_segUsuarioEdita, p_segMaquinaOrigen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Presupuesto.pa_I_Gasto")]
		public int pa_I_Gasto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> p_codGasto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codPlantillaDeta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,2)")] System.Nullable<decimal> p_monTotal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,2)")] System.Nullable<decimal> p_cntCantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(16)")] string p_numDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(120)")] string p_gloObservacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_fecGasto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codEmpleadoResp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segUsuarioCrea, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segMaquinaOrigen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codGasto, p_codPlantillaDeta, p_monTotal, p_cntCantidad, p_numDocumento, p_gloObservacion, p_fecGasto, p_codEmpleadoResp, p_segUsuarioCrea, p_segMaquinaOrigen);
			p_codGasto = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Presupuesto.pa_I_PlantillaDeta")]
		public int pa_I_PlantillaDeta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> p_codPlantillaDeta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codPlantilla, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string p_gloDescripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(12,2)")] System.Nullable<decimal> p_monEstimado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,2)")] System.Nullable<decimal> p_cntCantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_fecEjecucion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1)")] string p_indPlantilla, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codPartida, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segUsuarioCrea, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segMaquinaOrigen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codPlantillaDeta, p_codPlantilla, p_gloDescripcion, p_monEstimado, p_cntCantidad, p_fecEjecucion, p_indPlantilla, p_codPartida, p_segUsuarioCrea, p_segMaquinaOrigen);
			p_codPlantillaDeta = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Presupuesto.pa_I_PlantillaDetaRefer")]
		public int pa_I_PlantillaDetaRefer([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> p_codPlantillaDeta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codPlantillaDetaRefer, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codPlantilla, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segUsuarioCrea, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segMaquinaOrigen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codPlantillaDeta, p_codPlantillaDetaRefer, p_codPlantilla, p_segUsuarioCrea, p_segMaquinaOrigen);
			p_codPlantillaDeta = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Presupuesto.pa_S_Gasto")]
		public ISingleResult<pa_S_GastoResult> pa_S_Gasto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codGasto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codPlantillaDeta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codGasto, p_codPlantillaDeta);
			return ((ISingleResult<pa_S_GastoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Presupuesto.pa_S_GastoPagina")]
		public ISingleResult<pa_S_GastoPaginaResult> pa_S_GastoPagina([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_NumPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_TamPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string p_OrdenPor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string p_OrdenTipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codGasto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codPlantillaDeta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_NumPagina, p_TamPagina, p_OrdenPor, p_OrdenTipo, p_codGasto, p_codPlantillaDeta);
			return ((ISingleResult<pa_S_GastoPaginaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Presupuesto.pa_S_Partida")]
		public ISingleResult<pa_S_PartidaResult> pa_S_Partida()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<pa_S_PartidaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Presupuesto.pa_S_Plantilla")]
		public ISingleResult<pa_S_PlantillaResult> pa_S_Plantilla([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codPlantilla, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_anio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codArea)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codPlantilla, p_anio, p_codArea);
			return ((ISingleResult<pa_S_PlantillaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Presupuesto.pa_S_PlantillaDeta")]
		public ISingleResult<pa_S_PlantillaDetaResult> pa_S_PlantillaDeta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codPlantillaDeta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_anio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codArea, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codRegEstado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codPlantillaDeta, p_anio, p_codArea, p_codRegEstado);
			return ((ISingleResult<pa_S_PlantillaDetaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Presupuesto.pa_S_PlantillaDetaPagina")]
		public ISingleResult<pa_S_PlantillaDetaPaginaResult> pa_S_PlantillaDetaPagina([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_NumPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_TamPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string p_OrdenPor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string p_OrdenTipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_anio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codArea, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codRegEstado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_NumPagina, p_TamPagina, p_OrdenPor, p_OrdenTipo, p_anio, p_codArea, p_codRegEstado);
			return ((ISingleResult<pa_S_PlantillaDetaPaginaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Presupuesto.pa_U_Gasto")]
		public int pa_U_Gasto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codGasto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(12,2)")] System.Nullable<decimal> p_monTotal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,2)")] System.Nullable<decimal> p_cntCantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(16)")] string p_numDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(120)")] string p_gloObservacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_fecGasto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codEmpleadoResp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segUsuarioEdita, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segMaquinaOrigen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codGasto, p_monTotal, p_cntCantidad, p_numDocumento, p_gloObservacion, p_fecGasto, p_codEmpleadoResp, p_segUsuarioEdita, p_segMaquinaOrigen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Presupuesto.pa_U_Plantilla_Estado")]
		public int pa_U_Plantilla_Estado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codPlantilla, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codRegEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segUsuarioEdita, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segMaquinaOrigen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codPlantilla, p_codRegEstado, p_segUsuarioEdita, p_segMaquinaOrigen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Presupuesto.pa_U_PlantillaDeta")]
		public int pa_U_PlantillaDeta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codPlantillaDeta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string p_gloDescripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(12,2)")] System.Nullable<decimal> p_monEstimado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,2)")] System.Nullable<decimal> p_cntCantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_fecEjecucion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codPartida, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segUsuarioEdita, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segMaquinaOrigen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codPlantillaDeta, p_gloDescripcion, p_monEstimado, p_cntCantidad, p_fecEjecucion, p_codPartida, p_segUsuarioEdita, p_segMaquinaOrigen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Presupuesto.pa_U_PlantillaDetaAprob")]
		public int pa_U_PlantillaDetaAprob([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codPlantillaDeta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codEmpleadoAprueba, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segUsuarioEdita, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segMaquinaOrigen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codPlantillaDeta, p_codEmpleadoAprueba, p_segUsuarioEdita, p_segMaquinaOrigen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="RecursosHumanos.pa_S_Area")]
		public ISingleResult<pa_S_AreaResult> pa_S_Area()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<pa_S_AreaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="RecursosHumanos.pa_S_Empleado")]
		public ISingleResult<pa_S_EmpleadoResult> pa_S_Empleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codArea, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string p_desNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string p_desApellido)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codEmpleado, p_codArea, p_desNombre, p_desApellido);
			return ((ISingleResult<pa_S_EmpleadoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Presupuesto.pa_S_Presupuesto")]
		public ISingleResult<pa_S_PresupuestoResult> pa_S_Presupuesto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_numAnio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_numAnio);
			return ((ISingleResult<pa_S_PresupuestoResult>)(result.ReturnValue));
		}
	}
	
	public partial class pa_S_EmpleadoLoginResult
	{
		
		private int _codEmpleado;
		
		private int _codCargo;
		
		private int _codArea;
		
		private string _desNombre;
		
		private string _desApellido;
		
		public pa_S_EmpleadoLoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleado", DbType="Int NOT NULL")]
		public int codEmpleado
		{
			get
			{
				return this._codEmpleado;
			}
			set
			{
				if ((this._codEmpleado != value))
				{
					this._codEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCargo", DbType="Int NOT NULL")]
		public int codCargo
		{
			get
			{
				return this._codCargo;
			}
			set
			{
				if ((this._codCargo != value))
				{
					this._codCargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codArea", DbType="Int NOT NULL")]
		public int codArea
		{
			get
			{
				return this._codArea;
			}
			set
			{
				if ((this._codArea != value))
				{
					this._codArea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desNombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string desNombre
		{
			get
			{
				return this._desNombre;
			}
			set
			{
				if ((this._desNombre != value))
				{
					this._desNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desApellido", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string desApellido
		{
			get
			{
				return this._desApellido;
			}
			set
			{
				if ((this._desApellido != value))
				{
					this._desApellido = value;
				}
			}
		}
	}
	
	public partial class pa_S_GastoResult
	{
		
		private int _codGasto;
		
		private int _codPlantillaDeta;
		
		private decimal _monTotal;
		
		private decimal _cntCantidad;
		
		private string _numDocumento;
		
		private string _gloObservacion;
		
		private System.DateTime _fecGasto;
		
		private int _codEmpleadoResp;
		
		private string _codEmpleadoRespNombre;
		
		private string _segUsuarioCrea;
		
		private string _segUsuarioEdita;
		
		private System.DateTime _segFechaCrea;
		
		private System.Nullable<System.DateTime> _segFechaEdita;
		
		private string _segMaquinaOrigen;
		
		public pa_S_GastoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codGasto", DbType="Int NOT NULL")]
		public int codGasto
		{
			get
			{
				return this._codGasto;
			}
			set
			{
				if ((this._codGasto != value))
				{
					this._codGasto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPlantillaDeta", DbType="Int NOT NULL")]
		public int codPlantillaDeta
		{
			get
			{
				return this._codPlantillaDeta;
			}
			set
			{
				if ((this._codPlantillaDeta != value))
				{
					this._codPlantillaDeta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monTotal", DbType="Decimal(12,2) NOT NULL")]
		public decimal monTotal
		{
			get
			{
				return this._monTotal;
			}
			set
			{
				if ((this._monTotal != value))
				{
					this._monTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntCantidad", DbType="Decimal(10,2) NOT NULL")]
		public decimal cntCantidad
		{
			get
			{
				return this._cntCantidad;
			}
			set
			{
				if ((this._cntCantidad != value))
				{
					this._cntCantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numDocumento", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string numDocumento
		{
			get
			{
				return this._numDocumento;
			}
			set
			{
				if ((this._numDocumento != value))
				{
					this._numDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gloObservacion", DbType="NVarChar(120)")]
		public string gloObservacion
		{
			get
			{
				return this._gloObservacion;
			}
			set
			{
				if ((this._gloObservacion != value))
				{
					this._gloObservacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecGasto", DbType="DateTime NOT NULL")]
		public System.DateTime fecGasto
		{
			get
			{
				return this._fecGasto;
			}
			set
			{
				if ((this._fecGasto != value))
				{
					this._fecGasto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleadoResp", DbType="Int NOT NULL")]
		public int codEmpleadoResp
		{
			get
			{
				return this._codEmpleadoResp;
			}
			set
			{
				if ((this._codEmpleadoResp != value))
				{
					this._codEmpleadoResp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleadoRespNombre", DbType="VarChar(81)")]
		public string codEmpleadoRespNombre
		{
			get
			{
				return this._codEmpleadoRespNombre;
			}
			set
			{
				if ((this._codEmpleadoRespNombre != value))
				{
					this._codEmpleadoRespNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioCrea", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segUsuarioCrea
		{
			get
			{
				return this._segUsuarioCrea;
			}
			set
			{
				if ((this._segUsuarioCrea != value))
				{
					this._segUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioEdita", DbType="VarChar(25)")]
		public string segUsuarioEdita
		{
			get
			{
				return this._segUsuarioEdita;
			}
			set
			{
				if ((this._segUsuarioEdita != value))
				{
					this._segUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaCrea", DbType="DateTime NOT NULL")]
		public System.DateTime segFechaCrea
		{
			get
			{
				return this._segFechaCrea;
			}
			set
			{
				if ((this._segFechaCrea != value))
				{
					this._segFechaCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> segFechaEdita
		{
			get
			{
				return this._segFechaEdita;
			}
			set
			{
				if ((this._segFechaEdita != value))
				{
					this._segFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segMaquinaOrigen", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segMaquinaOrigen
		{
			get
			{
				return this._segMaquinaOrigen;
			}
			set
			{
				if ((this._segMaquinaOrigen != value))
				{
					this._segMaquinaOrigen = value;
				}
			}
		}
	}
	
	public partial class pa_S_GastoPaginaResult
	{
		
		private int _codGasto;
		
		private int _codPlantillaDeta;
		
		private decimal _monTotal;
		
		private decimal _cntCantidad;
		
		private string _numDocumento;
		
		private string _gloObservacion;
		
		private System.DateTime _fecGasto;
		
		private int _codEmpleadoResp;
		
		private string _codEmpleadoRespNombre;
		
		private string _segUsuarioCrea;
		
		private string _segUsuarioEdita;
		
		private System.DateTime _segFechaCrea;
		
		private System.Nullable<System.DateTime> _segFechaEdita;
		
		private string _segMaquinaOrigen;
		
		private System.Nullable<int> _TOTALROWS;
		
		private System.Nullable<long> _ROWNUM;
		
		public pa_S_GastoPaginaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codGasto", DbType="Int NOT NULL")]
		public int codGasto
		{
			get
			{
				return this._codGasto;
			}
			set
			{
				if ((this._codGasto != value))
				{
					this._codGasto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPlantillaDeta", DbType="Int NOT NULL")]
		public int codPlantillaDeta
		{
			get
			{
				return this._codPlantillaDeta;
			}
			set
			{
				if ((this._codPlantillaDeta != value))
				{
					this._codPlantillaDeta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monTotal", DbType="Decimal(12,2) NOT NULL")]
		public decimal monTotal
		{
			get
			{
				return this._monTotal;
			}
			set
			{
				if ((this._monTotal != value))
				{
					this._monTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntCantidad", DbType="Decimal(10,2) NOT NULL")]
		public decimal cntCantidad
		{
			get
			{
				return this._cntCantidad;
			}
			set
			{
				if ((this._cntCantidad != value))
				{
					this._cntCantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numDocumento", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string numDocumento
		{
			get
			{
				return this._numDocumento;
			}
			set
			{
				if ((this._numDocumento != value))
				{
					this._numDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gloObservacion", DbType="NVarChar(120)")]
		public string gloObservacion
		{
			get
			{
				return this._gloObservacion;
			}
			set
			{
				if ((this._gloObservacion != value))
				{
					this._gloObservacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecGasto", DbType="DateTime NOT NULL")]
		public System.DateTime fecGasto
		{
			get
			{
				return this._fecGasto;
			}
			set
			{
				if ((this._fecGasto != value))
				{
					this._fecGasto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleadoResp", DbType="Int NOT NULL")]
		public int codEmpleadoResp
		{
			get
			{
				return this._codEmpleadoResp;
			}
			set
			{
				if ((this._codEmpleadoResp != value))
				{
					this._codEmpleadoResp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleadoRespNombre", DbType="VarChar(81)")]
		public string codEmpleadoRespNombre
		{
			get
			{
				return this._codEmpleadoRespNombre;
			}
			set
			{
				if ((this._codEmpleadoRespNombre != value))
				{
					this._codEmpleadoRespNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioCrea", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segUsuarioCrea
		{
			get
			{
				return this._segUsuarioCrea;
			}
			set
			{
				if ((this._segUsuarioCrea != value))
				{
					this._segUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioEdita", DbType="VarChar(25)")]
		public string segUsuarioEdita
		{
			get
			{
				return this._segUsuarioEdita;
			}
			set
			{
				if ((this._segUsuarioEdita != value))
				{
					this._segUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaCrea", DbType="DateTime NOT NULL")]
		public System.DateTime segFechaCrea
		{
			get
			{
				return this._segFechaCrea;
			}
			set
			{
				if ((this._segFechaCrea != value))
				{
					this._segFechaCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> segFechaEdita
		{
			get
			{
				return this._segFechaEdita;
			}
			set
			{
				if ((this._segFechaEdita != value))
				{
					this._segFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segMaquinaOrigen", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segMaquinaOrigen
		{
			get
			{
				return this._segMaquinaOrigen;
			}
			set
			{
				if ((this._segMaquinaOrigen != value))
				{
					this._segMaquinaOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTALROWS", DbType="Int")]
		public System.Nullable<int> TOTALROWS
		{
			get
			{
				return this._TOTALROWS;
			}
			set
			{
				if ((this._TOTALROWS != value))
				{
					this._TOTALROWS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWNUM", DbType="BigInt")]
		public System.Nullable<long> ROWNUM
		{
			get
			{
				return this._ROWNUM;
			}
			set
			{
				if ((this._ROWNUM != value))
				{
					this._ROWNUM = value;
				}
			}
		}
	}
	
	public partial class pa_S_PartidaResult
	{
		
		private int _codPartida;
		
		private string _desNombre;
		
		public pa_S_PartidaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPartida", DbType="Int NOT NULL")]
		public int codPartida
		{
			get
			{
				return this._codPartida;
			}
			set
			{
				if ((this._codPartida != value))
				{
					this._codPartida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desNombre", DbType="NVarChar(71)")]
		public string desNombre
		{
			get
			{
				return this._desNombre;
			}
			set
			{
				if ((this._desNombre != value))
				{
					this._desNombre = value;
				}
			}
		}
	}
	
	public partial class pa_S_PlantillaResult
	{
		
		private int _codPlantilla;
		
		private string _numPlantilla;
		
		private string _nombrePresupuesto;
		
		private int _numAnio;
		
		private System.Nullable<System.DateTime> _fecCierre;
		
		private string _codAreaNombre;
		
		private string _desEmpleadoActual;
		
		private string _codCargoNombre;
		
		private string _desEmpleadoElabora;
		
		private System.Nullable<System.DateTime> _segFechaEdita;
		
		private string _segUsuarioEdita;
		
		private System.DateTime _segFechaCrea;
		
		private string _segUsuarioCrea;
		
		private System.Nullable<decimal> _monMaximo;
		
		private int _numDiasExtemporaneo;
		
		private string _EstadoPlantilla;
		
		private System.Nullable<decimal> _monEstimadoTotalxArea;
		
		public pa_S_PlantillaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPlantilla", DbType="Int NOT NULL")]
		public int codPlantilla
		{
			get
			{
				return this._codPlantilla;
			}
			set
			{
				if ((this._codPlantilla != value))
				{
					this._codPlantilla = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numPlantilla", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string numPlantilla
		{
			get
			{
				return this._numPlantilla;
			}
			set
			{
				if ((this._numPlantilla != value))
				{
					this._numPlantilla = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrePresupuesto", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string nombrePresupuesto
		{
			get
			{
				return this._nombrePresupuesto;
			}
			set
			{
				if ((this._nombrePresupuesto != value))
				{
					this._nombrePresupuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numAnio", DbType="Int NOT NULL")]
		public int numAnio
		{
			get
			{
				return this._numAnio;
			}
			set
			{
				if ((this._numAnio != value))
				{
					this._numAnio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecCierre", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecCierre
		{
			get
			{
				return this._fecCierre;
			}
			set
			{
				if ((this._fecCierre != value))
				{
					this._fecCierre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codAreaNombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string codAreaNombre
		{
			get
			{
				return this._codAreaNombre;
			}
			set
			{
				if ((this._codAreaNombre != value))
				{
					this._codAreaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desEmpleadoActual", DbType="VarChar(82) NOT NULL", CanBeNull=false)]
		public string desEmpleadoActual
		{
			get
			{
				return this._desEmpleadoActual;
			}
			set
			{
				if ((this._desEmpleadoActual != value))
				{
					this._desEmpleadoActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCargoNombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string codCargoNombre
		{
			get
			{
				return this._codCargoNombre;
			}
			set
			{
				if ((this._codCargoNombre != value))
				{
					this._codCargoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desEmpleadoElabora", DbType="VarChar(82) NOT NULL", CanBeNull=false)]
		public string desEmpleadoElabora
		{
			get
			{
				return this._desEmpleadoElabora;
			}
			set
			{
				if ((this._desEmpleadoElabora != value))
				{
					this._desEmpleadoElabora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> segFechaEdita
		{
			get
			{
				return this._segFechaEdita;
			}
			set
			{
				if ((this._segFechaEdita != value))
				{
					this._segFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioEdita", DbType="VarChar(25)")]
		public string segUsuarioEdita
		{
			get
			{
				return this._segUsuarioEdita;
			}
			set
			{
				if ((this._segUsuarioEdita != value))
				{
					this._segUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaCrea", DbType="DateTime NOT NULL")]
		public System.DateTime segFechaCrea
		{
			get
			{
				return this._segFechaCrea;
			}
			set
			{
				if ((this._segFechaCrea != value))
				{
					this._segFechaCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioCrea", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segUsuarioCrea
		{
			get
			{
				return this._segUsuarioCrea;
			}
			set
			{
				if ((this._segUsuarioCrea != value))
				{
					this._segUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monMaximo", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> monMaximo
		{
			get
			{
				return this._monMaximo;
			}
			set
			{
				if ((this._monMaximo != value))
				{
					this._monMaximo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numDiasExtemporaneo", DbType="Int NOT NULL")]
		public int numDiasExtemporaneo
		{
			get
			{
				return this._numDiasExtemporaneo;
			}
			set
			{
				if ((this._numDiasExtemporaneo != value))
				{
					this._numDiasExtemporaneo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoPlantilla", DbType="VarChar(11)")]
		public string EstadoPlantilla
		{
			get
			{
				return this._EstadoPlantilla;
			}
			set
			{
				if ((this._EstadoPlantilla != value))
				{
					this._EstadoPlantilla = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monEstimadoTotalxArea", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> monEstimadoTotalxArea
		{
			get
			{
				return this._monEstimadoTotalxArea;
			}
			set
			{
				if ((this._monEstimadoTotalxArea != value))
				{
					this._monEstimadoTotalxArea = value;
				}
			}
		}
	}
	
	public partial class pa_S_PlantillaDetaResult
	{
		
		private int _codPlantillaDeta;
		
		private int _codPlantilla;
		
		private System.Nullable<int> _codEmpleadoAprueba;
		
		private string _codEmpleadoApruebaNombre;
		
		private string _gloDescripcion;
		
		private decimal _monEstimado;
		
		private decimal _cntCantidad;
		
		private int _codRegEstado;
		
		private string _codRegEstadoNombre;
		
		private System.Nullable<System.DateTime> _fecEjecucion;
		
		private System.Nullable<int> _codEmpleadoRespon;
		
		private string _codEmpleadoResponRespon;
		
		private string _indPlantilla;
		
		private string _indPlantillaTipo;
		
		private int _codPartida;
		
		private string _numPartida;
		
		private string _segUsuarioCrea;
		
		private string _segUsuarioEdita;
		
		private System.DateTime _segFechaCrea;
		
		private System.Nullable<System.DateTime> _segFechaEdita;
		
		private string _segMaquinaOrigen;
		
		private string _codPartidaNombre;
		
		private string _codNumero;
		
		private int _codArea;
		
		private string _codAreaNombre;
		
		public pa_S_PlantillaDetaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPlantillaDeta", DbType="Int NOT NULL")]
		public int codPlantillaDeta
		{
			get
			{
				return this._codPlantillaDeta;
			}
			set
			{
				if ((this._codPlantillaDeta != value))
				{
					this._codPlantillaDeta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPlantilla", DbType="Int NOT NULL")]
		public int codPlantilla
		{
			get
			{
				return this._codPlantilla;
			}
			set
			{
				if ((this._codPlantilla != value))
				{
					this._codPlantilla = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleadoAprueba", DbType="Int")]
		public System.Nullable<int> codEmpleadoAprueba
		{
			get
			{
				return this._codEmpleadoAprueba;
			}
			set
			{
				if ((this._codEmpleadoAprueba != value))
				{
					this._codEmpleadoAprueba = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleadoApruebaNombre", DbType="VarChar(82)")]
		public string codEmpleadoApruebaNombre
		{
			get
			{
				return this._codEmpleadoApruebaNombre;
			}
			set
			{
				if ((this._codEmpleadoApruebaNombre != value))
				{
					this._codEmpleadoApruebaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gloDescripcion", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string gloDescripcion
		{
			get
			{
				return this._gloDescripcion;
			}
			set
			{
				if ((this._gloDescripcion != value))
				{
					this._gloDescripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monEstimado", DbType="Decimal(12,2) NOT NULL")]
		public decimal monEstimado
		{
			get
			{
				return this._monEstimado;
			}
			set
			{
				if ((this._monEstimado != value))
				{
					this._monEstimado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntCantidad", DbType="Decimal(10,2) NOT NULL")]
		public decimal cntCantidad
		{
			get
			{
				return this._cntCantidad;
			}
			set
			{
				if ((this._cntCantidad != value))
				{
					this._cntCantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegEstado", DbType="Int NOT NULL")]
		public int codRegEstado
		{
			get
			{
				return this._codRegEstado;
			}
			set
			{
				if ((this._codRegEstado != value))
				{
					this._codRegEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegEstadoNombre", DbType="VarChar(13)")]
		public string codRegEstadoNombre
		{
			get
			{
				return this._codRegEstadoNombre;
			}
			set
			{
				if ((this._codRegEstadoNombre != value))
				{
					this._codRegEstadoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecEjecucion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecEjecucion
		{
			get
			{
				return this._fecEjecucion;
			}
			set
			{
				if ((this._fecEjecucion != value))
				{
					this._fecEjecucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleadoRespon", DbType="Int")]
		public System.Nullable<int> codEmpleadoRespon
		{
			get
			{
				return this._codEmpleadoRespon;
			}
			set
			{
				if ((this._codEmpleadoRespon != value))
				{
					this._codEmpleadoRespon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleadoResponRespon", DbType="VarChar(82)")]
		public string codEmpleadoResponRespon
		{
			get
			{
				return this._codEmpleadoResponRespon;
			}
			set
			{
				if ((this._codEmpleadoResponRespon != value))
				{
					this._codEmpleadoResponRespon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indPlantilla", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string indPlantilla
		{
			get
			{
				return this._indPlantilla;
			}
			set
			{
				if ((this._indPlantilla != value))
				{
					this._indPlantilla = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indPlantillaTipo", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string indPlantillaTipo
		{
			get
			{
				return this._indPlantillaTipo;
			}
			set
			{
				if ((this._indPlantillaTipo != value))
				{
					this._indPlantillaTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPartida", DbType="Int NOT NULL")]
		public int codPartida
		{
			get
			{
				return this._codPartida;
			}
			set
			{
				if ((this._codPartida != value))
				{
					this._codPartida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numPartida", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string numPartida
		{
			get
			{
				return this._numPartida;
			}
			set
			{
				if ((this._numPartida != value))
				{
					this._numPartida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioCrea", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segUsuarioCrea
		{
			get
			{
				return this._segUsuarioCrea;
			}
			set
			{
				if ((this._segUsuarioCrea != value))
				{
					this._segUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioEdita", DbType="VarChar(25)")]
		public string segUsuarioEdita
		{
			get
			{
				return this._segUsuarioEdita;
			}
			set
			{
				if ((this._segUsuarioEdita != value))
				{
					this._segUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaCrea", DbType="DateTime NOT NULL")]
		public System.DateTime segFechaCrea
		{
			get
			{
				return this._segFechaCrea;
			}
			set
			{
				if ((this._segFechaCrea != value))
				{
					this._segFechaCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> segFechaEdita
		{
			get
			{
				return this._segFechaEdita;
			}
			set
			{
				if ((this._segFechaEdita != value))
				{
					this._segFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segMaquinaOrigen", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segMaquinaOrigen
		{
			get
			{
				return this._segMaquinaOrigen;
			}
			set
			{
				if ((this._segMaquinaOrigen != value))
				{
					this._segMaquinaOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPartidaNombre", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string codPartidaNombre
		{
			get
			{
				return this._codPartidaNombre;
			}
			set
			{
				if ((this._codPartidaNombre != value))
				{
					this._codPartidaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codNumero", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string codNumero
		{
			get
			{
				return this._codNumero;
			}
			set
			{
				if ((this._codNumero != value))
				{
					this._codNumero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codArea", DbType="Int NOT NULL")]
		public int codArea
		{
			get
			{
				return this._codArea;
			}
			set
			{
				if ((this._codArea != value))
				{
					this._codArea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codAreaNombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string codAreaNombre
		{
			get
			{
				return this._codAreaNombre;
			}
			set
			{
				if ((this._codAreaNombre != value))
				{
					this._codAreaNombre = value;
				}
			}
		}
	}
	
	public partial class pa_S_PlantillaDetaPaginaResult
	{
		
		private int _codPlantillaDeta;
		
		private int _codPlantilla;
		
		private System.Nullable<int> _codEmpleadoAprueba;
		
		private string _codEmpleadoResponNombre;
		
		private string _gloDescripcion;
		
		private decimal _monEstimado;
		
		private decimal _cntCantidad;
		
		private int _codRegEstado;
		
		private string _codRegEstadoNombre;
		
		private System.Nullable<System.DateTime> _fecEjecucion;
		
		private System.Nullable<int> _codEmpleadoRespon;
		
		private string _codEmpleadoResponRespon;
		
		private string _indPlantilla;
		
		private string _indPlantillaTipo;
		
		private int _codPartida;
		
		private string _numPartida;
		
		private string _segUsuarioCrea;
		
		private string _segUsuarioEdita;
		
		private System.DateTime _segFechaCrea;
		
		private System.Nullable<System.DateTime> _segFechaEdita;
		
		private string _segMaquinaOrigen;
		
		private string _codPartidaNombre;
		
		private string _codNumero;
		
		private int _codArea;
		
		private string _codAreaNombre;
		
		private System.Nullable<int> _TOTALROWS;
		
		private System.Nullable<long> _ROWNUM;
		
		public pa_S_PlantillaDetaPaginaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPlantillaDeta", DbType="Int NOT NULL")]
		public int codPlantillaDeta
		{
			get
			{
				return this._codPlantillaDeta;
			}
			set
			{
				if ((this._codPlantillaDeta != value))
				{
					this._codPlantillaDeta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPlantilla", DbType="Int NOT NULL")]
		public int codPlantilla
		{
			get
			{
				return this._codPlantilla;
			}
			set
			{
				if ((this._codPlantilla != value))
				{
					this._codPlantilla = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleadoAprueba", DbType="Int")]
		public System.Nullable<int> codEmpleadoAprueba
		{
			get
			{
				return this._codEmpleadoAprueba;
			}
			set
			{
				if ((this._codEmpleadoAprueba != value))
				{
					this._codEmpleadoAprueba = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleadoResponNombre", DbType="VarChar(82)")]
		public string codEmpleadoResponNombre
		{
			get
			{
				return this._codEmpleadoResponNombre;
			}
			set
			{
				if ((this._codEmpleadoResponNombre != value))
				{
					this._codEmpleadoResponNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gloDescripcion", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string gloDescripcion
		{
			get
			{
				return this._gloDescripcion;
			}
			set
			{
				if ((this._gloDescripcion != value))
				{
					this._gloDescripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monEstimado", DbType="Decimal(12,2) NOT NULL")]
		public decimal monEstimado
		{
			get
			{
				return this._monEstimado;
			}
			set
			{
				if ((this._monEstimado != value))
				{
					this._monEstimado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntCantidad", DbType="Decimal(10,2) NOT NULL")]
		public decimal cntCantidad
		{
			get
			{
				return this._cntCantidad;
			}
			set
			{
				if ((this._cntCantidad != value))
				{
					this._cntCantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegEstado", DbType="Int NOT NULL")]
		public int codRegEstado
		{
			get
			{
				return this._codRegEstado;
			}
			set
			{
				if ((this._codRegEstado != value))
				{
					this._codRegEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegEstadoNombre", DbType="VarChar(13)")]
		public string codRegEstadoNombre
		{
			get
			{
				return this._codRegEstadoNombre;
			}
			set
			{
				if ((this._codRegEstadoNombre != value))
				{
					this._codRegEstadoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecEjecucion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecEjecucion
		{
			get
			{
				return this._fecEjecucion;
			}
			set
			{
				if ((this._fecEjecucion != value))
				{
					this._fecEjecucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleadoRespon", DbType="Int")]
		public System.Nullable<int> codEmpleadoRespon
		{
			get
			{
				return this._codEmpleadoRespon;
			}
			set
			{
				if ((this._codEmpleadoRespon != value))
				{
					this._codEmpleadoRespon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleadoResponRespon", DbType="VarChar(82)")]
		public string codEmpleadoResponRespon
		{
			get
			{
				return this._codEmpleadoResponRespon;
			}
			set
			{
				if ((this._codEmpleadoResponRespon != value))
				{
					this._codEmpleadoResponRespon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indPlantilla", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string indPlantilla
		{
			get
			{
				return this._indPlantilla;
			}
			set
			{
				if ((this._indPlantilla != value))
				{
					this._indPlantilla = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indPlantillaTipo", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string indPlantillaTipo
		{
			get
			{
				return this._indPlantillaTipo;
			}
			set
			{
				if ((this._indPlantillaTipo != value))
				{
					this._indPlantillaTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPartida", DbType="Int NOT NULL")]
		public int codPartida
		{
			get
			{
				return this._codPartida;
			}
			set
			{
				if ((this._codPartida != value))
				{
					this._codPartida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numPartida", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string numPartida
		{
			get
			{
				return this._numPartida;
			}
			set
			{
				if ((this._numPartida != value))
				{
					this._numPartida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioCrea", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segUsuarioCrea
		{
			get
			{
				return this._segUsuarioCrea;
			}
			set
			{
				if ((this._segUsuarioCrea != value))
				{
					this._segUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioEdita", DbType="VarChar(25)")]
		public string segUsuarioEdita
		{
			get
			{
				return this._segUsuarioEdita;
			}
			set
			{
				if ((this._segUsuarioEdita != value))
				{
					this._segUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaCrea", DbType="DateTime NOT NULL")]
		public System.DateTime segFechaCrea
		{
			get
			{
				return this._segFechaCrea;
			}
			set
			{
				if ((this._segFechaCrea != value))
				{
					this._segFechaCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> segFechaEdita
		{
			get
			{
				return this._segFechaEdita;
			}
			set
			{
				if ((this._segFechaEdita != value))
				{
					this._segFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segMaquinaOrigen", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segMaquinaOrigen
		{
			get
			{
				return this._segMaquinaOrigen;
			}
			set
			{
				if ((this._segMaquinaOrigen != value))
				{
					this._segMaquinaOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPartidaNombre", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string codPartidaNombre
		{
			get
			{
				return this._codPartidaNombre;
			}
			set
			{
				if ((this._codPartidaNombre != value))
				{
					this._codPartidaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codNumero", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string codNumero
		{
			get
			{
				return this._codNumero;
			}
			set
			{
				if ((this._codNumero != value))
				{
					this._codNumero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codArea", DbType="Int NOT NULL")]
		public int codArea
		{
			get
			{
				return this._codArea;
			}
			set
			{
				if ((this._codArea != value))
				{
					this._codArea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codAreaNombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string codAreaNombre
		{
			get
			{
				return this._codAreaNombre;
			}
			set
			{
				if ((this._codAreaNombre != value))
				{
					this._codAreaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTALROWS", DbType="Int")]
		public System.Nullable<int> TOTALROWS
		{
			get
			{
				return this._TOTALROWS;
			}
			set
			{
				if ((this._TOTALROWS != value))
				{
					this._TOTALROWS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWNUM", DbType="BigInt")]
		public System.Nullable<long> ROWNUM
		{
			get
			{
				return this._ROWNUM;
			}
			set
			{
				if ((this._ROWNUM != value))
				{
					this._ROWNUM = value;
				}
			}
		}
	}
	
	public partial class pa_S_AreaResult
	{
		
		private int _codArea;
		
		private string _desNombre;
		
		private string _gloDescripcion;
		
		private bool _indActivo;
		
		private string _segUsuarioCrea;
		
		private string _segUsuarioEdita;
		
		private System.DateTime _segFechaCrea;
		
		private System.Nullable<System.DateTime> _segFechaEdita;
		
		private string _segMaquinaOrigen;
		
		private bool _indEliminado;
		
		public pa_S_AreaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codArea", DbType="Int NOT NULL")]
		public int codArea
		{
			get
			{
				return this._codArea;
			}
			set
			{
				if ((this._codArea != value))
				{
					this._codArea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desNombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string desNombre
		{
			get
			{
				return this._desNombre;
			}
			set
			{
				if ((this._desNombre != value))
				{
					this._desNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gloDescripcion", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string gloDescripcion
		{
			get
			{
				return this._gloDescripcion;
			}
			set
			{
				if ((this._gloDescripcion != value))
				{
					this._gloDescripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indActivo", DbType="Bit NOT NULL")]
		public bool indActivo
		{
			get
			{
				return this._indActivo;
			}
			set
			{
				if ((this._indActivo != value))
				{
					this._indActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioCrea", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segUsuarioCrea
		{
			get
			{
				return this._segUsuarioCrea;
			}
			set
			{
				if ((this._segUsuarioCrea != value))
				{
					this._segUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioEdita", DbType="VarChar(25)")]
		public string segUsuarioEdita
		{
			get
			{
				return this._segUsuarioEdita;
			}
			set
			{
				if ((this._segUsuarioEdita != value))
				{
					this._segUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaCrea", DbType="DateTime NOT NULL")]
		public System.DateTime segFechaCrea
		{
			get
			{
				return this._segFechaCrea;
			}
			set
			{
				if ((this._segFechaCrea != value))
				{
					this._segFechaCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> segFechaEdita
		{
			get
			{
				return this._segFechaEdita;
			}
			set
			{
				if ((this._segFechaEdita != value))
				{
					this._segFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segMaquinaOrigen", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segMaquinaOrigen
		{
			get
			{
				return this._segMaquinaOrigen;
			}
			set
			{
				if ((this._segMaquinaOrigen != value))
				{
					this._segMaquinaOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indEliminado", DbType="Bit NOT NULL")]
		public bool indEliminado
		{
			get
			{
				return this._indEliminado;
			}
			set
			{
				if ((this._indEliminado != value))
				{
					this._indEliminado = value;
				}
			}
		}
	}
	
	public partial class pa_S_EmpleadoResult
	{
		
		private int _codEmpleado;
		
		private int _codPersona;
		
		private int _codCargo;
		
		private string _codCargoNombre;
		
		private int _codArea;
		
		private string _codAreaNombre;
		
		private string _desNombre;
		
		private string _desApellido;
		
		private bool _indActivo;
		
		private string _segUsuarioCrea;
		
		private string _segUsuarioEdita;
		
		private System.DateTime _segFechaCrea;
		
		private System.Nullable<System.DateTime> _segFechaEdita;
		
		private string _segMaquinaOrigen;
		
		private bool _indEliminado;
		
		public pa_S_EmpleadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleado", DbType="Int NOT NULL")]
		public int codEmpleado
		{
			get
			{
				return this._codEmpleado;
			}
			set
			{
				if ((this._codEmpleado != value))
				{
					this._codEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPersona", DbType="Int NOT NULL")]
		public int codPersona
		{
			get
			{
				return this._codPersona;
			}
			set
			{
				if ((this._codPersona != value))
				{
					this._codPersona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCargo", DbType="Int NOT NULL")]
		public int codCargo
		{
			get
			{
				return this._codCargo;
			}
			set
			{
				if ((this._codCargo != value))
				{
					this._codCargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCargoNombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string codCargoNombre
		{
			get
			{
				return this._codCargoNombre;
			}
			set
			{
				if ((this._codCargoNombre != value))
				{
					this._codCargoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codArea", DbType="Int NOT NULL")]
		public int codArea
		{
			get
			{
				return this._codArea;
			}
			set
			{
				if ((this._codArea != value))
				{
					this._codArea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codAreaNombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string codAreaNombre
		{
			get
			{
				return this._codAreaNombre;
			}
			set
			{
				if ((this._codAreaNombre != value))
				{
					this._codAreaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desNombre", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string desNombre
		{
			get
			{
				return this._desNombre;
			}
			set
			{
				if ((this._desNombre != value))
				{
					this._desNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desApellido", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string desApellido
		{
			get
			{
				return this._desApellido;
			}
			set
			{
				if ((this._desApellido != value))
				{
					this._desApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indActivo", DbType="Bit NOT NULL")]
		public bool indActivo
		{
			get
			{
				return this._indActivo;
			}
			set
			{
				if ((this._indActivo != value))
				{
					this._indActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioCrea", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segUsuarioCrea
		{
			get
			{
				return this._segUsuarioCrea;
			}
			set
			{
				if ((this._segUsuarioCrea != value))
				{
					this._segUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioEdita", DbType="VarChar(25)")]
		public string segUsuarioEdita
		{
			get
			{
				return this._segUsuarioEdita;
			}
			set
			{
				if ((this._segUsuarioEdita != value))
				{
					this._segUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaCrea", DbType="DateTime NOT NULL")]
		public System.DateTime segFechaCrea
		{
			get
			{
				return this._segFechaCrea;
			}
			set
			{
				if ((this._segFechaCrea != value))
				{
					this._segFechaCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> segFechaEdita
		{
			get
			{
				return this._segFechaEdita;
			}
			set
			{
				if ((this._segFechaEdita != value))
				{
					this._segFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segMaquinaOrigen", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segMaquinaOrigen
		{
			get
			{
				return this._segMaquinaOrigen;
			}
			set
			{
				if ((this._segMaquinaOrigen != value))
				{
					this._segMaquinaOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indEliminado", DbType="Bit NOT NULL")]
		public bool indEliminado
		{
			get
			{
				return this._indEliminado;
			}
			set
			{
				if ((this._indEliminado != value))
				{
					this._indEliminado = value;
				}
			}
		}
	}
	
	public partial class pa_S_PresupuestoResult
	{
		
		private int _codPresupuesto;
		
		private string _desNombre;
		
		private int _numAnio;
		
		private System.Nullable<System.DateTime> _fecInicio;
		
		private System.Nullable<System.DateTime> _fecCierre;
		
		private int _codRegEstado;
		
		private string _segUsuarioCrea;
		
		private string _segUsuarioEdita;
		
		private System.DateTime _segFechaCrea;
		
		private System.Nullable<System.DateTime> _segFechaEdita;
		
		private string _segMaquinaOrigen;
		
		private bool _indEliminado;
		
		private System.Nullable<decimal> _monTotalPresupuesto;
		
		private System.Nullable<decimal> _monTotalSolicitado;
		
		private System.Nullable<decimal> _monTotalGastado;
		
		public pa_S_PresupuestoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPresupuesto", DbType="Int NOT NULL")]
		public int codPresupuesto
		{
			get
			{
				return this._codPresupuesto;
			}
			set
			{
				if ((this._codPresupuesto != value))
				{
					this._codPresupuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desNombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string desNombre
		{
			get
			{
				return this._desNombre;
			}
			set
			{
				if ((this._desNombre != value))
				{
					this._desNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numAnio", DbType="Int NOT NULL")]
		public int numAnio
		{
			get
			{
				return this._numAnio;
			}
			set
			{
				if ((this._numAnio != value))
				{
					this._numAnio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecInicio", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecInicio
		{
			get
			{
				return this._fecInicio;
			}
			set
			{
				if ((this._fecInicio != value))
				{
					this._fecInicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecCierre", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecCierre
		{
			get
			{
				return this._fecCierre;
			}
			set
			{
				if ((this._fecCierre != value))
				{
					this._fecCierre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegEstado", DbType="Int NOT NULL")]
		public int codRegEstado
		{
			get
			{
				return this._codRegEstado;
			}
			set
			{
				if ((this._codRegEstado != value))
				{
					this._codRegEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioCrea", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segUsuarioCrea
		{
			get
			{
				return this._segUsuarioCrea;
			}
			set
			{
				if ((this._segUsuarioCrea != value))
				{
					this._segUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioEdita", DbType="VarChar(25)")]
		public string segUsuarioEdita
		{
			get
			{
				return this._segUsuarioEdita;
			}
			set
			{
				if ((this._segUsuarioEdita != value))
				{
					this._segUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaCrea", DbType="DateTime NOT NULL")]
		public System.DateTime segFechaCrea
		{
			get
			{
				return this._segFechaCrea;
			}
			set
			{
				if ((this._segFechaCrea != value))
				{
					this._segFechaCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> segFechaEdita
		{
			get
			{
				return this._segFechaEdita;
			}
			set
			{
				if ((this._segFechaEdita != value))
				{
					this._segFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segMaquinaOrigen", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segMaquinaOrigen
		{
			get
			{
				return this._segMaquinaOrigen;
			}
			set
			{
				if ((this._segMaquinaOrigen != value))
				{
					this._segMaquinaOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indEliminado", DbType="Bit NOT NULL")]
		public bool indEliminado
		{
			get
			{
				return this._indEliminado;
			}
			set
			{
				if ((this._indEliminado != value))
				{
					this._indEliminado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monTotalPresupuesto", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> monTotalPresupuesto
		{
			get
			{
				return this._monTotalPresupuesto;
			}
			set
			{
				if ((this._monTotalPresupuesto != value))
				{
					this._monTotalPresupuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monTotalSolicitado", DbType="Decimal(38,4)")]
		public System.Nullable<decimal> monTotalSolicitado
		{
			get
			{
				return this._monTotalSolicitado;
			}
			set
			{
				if ((this._monTotalSolicitado != value))
				{
					this._monTotalSolicitado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monTotalGastado", DbType="Decimal(38,4)")]
		public System.Nullable<decimal> monTotalGastado
		{
			get
			{
				return this._monTotalGastado;
			}
			set
			{
				if ((this._monTotalGastado != value))
				{
					this._monTotalGastado = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
