//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByS.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelpMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ByS.Tools.HelpMessages", typeof(HelpMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡ Registro eliminado satisfactoriamente !.
        /// </summary>
        public static string Evento_DELETE {
            get {
                return ResourceManager.GetString("Evento_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Confirma eliminar el registro seleccionado ?.
        /// </summary>
        public static string Evento_DELETE_Confirma {
            get {
                return ResourceManager.GetString("Evento_DELETE_Confirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡ Registro tiene dependencia con otro nivel en la tabla !.
        /// </summary>
        public static string Evento_DEPEND {
            get {
                return ResourceManager.GetString("Evento_DEPEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡ Registro actualizado satisfactoriamente !.
        /// </summary>
        public static string Evento_EDIT {
            get {
                return ResourceManager.GetString("Evento_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Confirma la actualización del registro ...[ SI ]-[ NO ] ?.
        /// </summary>
        public static string Evento_EDIT_Confirma {
            get {
                return ResourceManager.GetString("Evento_EDIT_Confirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡ Registro insertado satisfactoriamente !.
        /// </summary>
        public static string Evento_NEW {
            get {
                return ResourceManager.GetString("Evento_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Confirma el ingreso del nuevo registro [ SI ]-[ NO ] ?.
        /// </summary>
        public static string Evento_NEW_Confirma {
            get {
                return ResourceManager.GetString("Evento_NEW_Confirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿ Confirma la cambiar de estado el documento ...[ SI ]-[ NO ] ?.
        /// </summary>
        public static string Evento_REVERTIR_Confirma {
            get {
                return ResourceManager.GetString("Evento_REVERTIR_Confirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡ Solo tiene permiso para visualizar datos del registro !.
        /// </summary>
        public static string Evento_VIEW {
            get {
                return ResourceManager.GetString("Evento_VIEW", resourceCulture);
            }
        }
    }
}
